'use strict';mix_d("SBXGwentV2Cards__multi-card-creative-desktop:multi-card-creative-desktop__kWdhdiR0","exports tslib @c/dom @c/metrics @c/logger @c/aui-feature-detect @c/aui-utils @p/a-ajax @c/pagemarker".split(" "),function(x,r,u,F,G,H,I,J,K){function h(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var v=h(u),y=h(F),L=h(G),M=h(H),N=h(I),O=h(J),P=h(K),k,Q=(k={},k.e="basebe.ClientErrors.4",k.i="basebe.Impressions.5",k.c="basebe.Clicks.4",k.s="basebe.Swipes.4",k.v="basebe.Viewabilities.4",
k.vc="basebe.VisualCompleteness.6",k),z=function(a,b){return"matches"in a?a.matches(b):"msMatchesSelector"in a?a.msMatchesSelector(b):"webkitMatchesSelector"in a?a.webkitMatchesSelector(b):0<=l(b,f().ownerDocument.body).indexOf(a)},f=function(a,b){b=b||v["default"].cardRoot;return!a||z(b,a)?b:b.querySelector(a)},l=function(a,b){return Array.prototype.slice.call((b||v["default"].cardRoot).querySelectorAll(a))},g=function(a,b){return(b=f("["+a+"]",b))?b.getAttribute(a):null},A=function(a,b){a:{for(var c=
"["+a+"]";b&&b!==v["default"].cardRoot;){if(z(b,c))break a;b=b.parentElement}b=null}return b?b.getAttribute(a):null},R=function(){var a=g("data-wl");return a?a.split(","):[]},S=function(){var a=f().ownerDocument.defaultView;return a.innerWidth+"x"+a.innerHeight},m=function(a,b){L["default"].log(a,"ERROR",b||"unknown")},U=function(a,b){var c,d=/\?([^#]+)/.exec(b.href);if(d){d=d[1].split("&");var e=null;try{for(var q=r.__values(d),f=q.next();!f.done;f=q.next()){var g=f.value;if(0===g.indexOf("ref_=")){e=
g;break}}}catch(w){var n={error:w}}finally{try{f&&!f.done&&(c=q.return)&&c.call(q)}finally{if(n)throw n.error;}}n=e?(n=e.split("=").pop()||"")?n.split("_"):[]:[]}else n=[];c={};if(5<n.length){c.el=n.pop()||null;a:{var k;try{for(var t=r.__values(n),h=t.next();!h.done;h=t.next()){var l=h.value;if(/^\d+$/.test(l)){var m=l;break a}}}catch(w){var p={error:w}}finally{try{h&&!h.done&&(k=t.return)&&k.call(t)}finally{if(p)throw p.error;}}m=null}c.index=m;c.asin=A("data-asin",b);c.type=A("data-avar",b)}a.c(c,
b)},V=function(a,b){var c=f().ownerDocument.defaultView,d=function(e){2!==e.button&&(U(a,b),e.metaKey||e.altKey||e.shiftKey||e.ctrlKey||1===e.button||"_blank"===b.target||(e.preventDefault(),c.setTimeout(function(){c.open(b.href,b.target||"_top")},50)))};b.addEventListener("click",d);b.addEventListener("auxclick",d)},W=function(a){l("[href]").forEach(function(b){V(a,b)})},X=function(a){return{id:g("data-asin",a),prime:!!f(".a-icon-prime",a),price:!!f(".a-price",a),savings:!!f('.a-price[data-a-strike="true"]',
a),rating:g("data-rt",a),badge:g("data-deal",a)}},Y=function(a,b){if(b)for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);return a},Z=function(a){var b=a.anonymizedRequestId,c=a.campaignId,d=a.slotName,e=function(a,e){try{y["default"].event(Y({anonymizedRequestId:b,campaignId:c,slotName:d},e),"base-be",Q[a],{ssd:!0})}catch(T){m(T,"event:"+(a||"?"))}};return{i:e.bind(null,"i"),v:e.bind(null,"v"),vc:e.bind(null,"vc"),c:e.bind(null,"c"),s:e.bind(null,"s"),e:function(a){e("e",a&&{name:a.name,
message:a.message,stack:a.stack})}}},aa=function(a,b){var c=null,d=null;a.addEventListener("touchstart",function(a){c=a.touches[0].pageX});a.addEventListener("touchmove",function(a){null===c&&(c=a.touches[0].pageX);d=a.touches[0].pageX});a.addEventListener("touchend",function(){null!==c&&null!==d&&b(d-c);c=d=null})},ba=function(a){if(M["default"].isSupported("touch")){var b=function(b){var c=Math.abs(b);30<c&&a.s({direction:0>b?"left":"right",length:c})};l("[data-track-swipe]").forEach(function(a){return aa(a,
b)})}},ca=function(a,b){var c=f().ownerDocument.defaultView,d,e=function(){d||(d=c.setTimeout(a,b))};e.cancel=function(){c.clearTimeout(d);d=0};return e},B=function(a,b,c){var d=(c||{}).ms||25,e=(c||{}).el||f().ownerDocument.defaultView,g=N["default"].throttle(b,d);e.addEventListener(a,g);return function(){e.removeEventListener(a,g)}},C=function(a,b,c){return 0<=a?Math.min(c-a,b-a):0<b?Math.min(Math.min(b,c),b-a):0},da=function(a,b){var c=function(){var a=b?b:f(),c=d,e=a.getBoundingClientRect();if(a=
e.width*e.height){var g=e.top,h=e.bottom,k=e.left,l=e.right,m=f().ownerDocument.defaultView;e=m.innerHeight;k=C(k,l,m.innerWidth);g=C(g,h,e);.5<=k*g/a?c():c.cancel()}},d=ca(function(){e();a.v(null,b)},1E3),e=B("scroll",c,void 0);c()},ea=function(a){var b=Date.now(),c=l("img"),d=c.length,e=0,f=function(){++e===d&&a.vc({delay:Date.now()-b})};c.forEach(function(a){null!==g("data-lazy",a)&&null!==g("data-src",a)?a.addEventListener("load",function(){a.src===a.dataset.src&&f()}):a.complete?f():a.addEventListener("load",
f)})},D=function(a,b){void 0===b&&(b=1);y["default"].count("sbxGwentClient"+a,b)},p={log:function(a){var b=f().ownerDocument.defaultView;var c=g("data-iid");(b=c&&b.sbxGwentClient&&"number"===typeof b.sbxGwentClient[c]?Date.now()-b.sbxGwentClient[c]:null)?D(a,b):D("NoPageTime")}},fa=function(a){var b=a.url,c=a.onSuccess,d=a.onError;b||d();O["default"].get(b,{success:function(a){a&&"ok"===a.status?c(a):d()},error:d,abort:d})},ha=function(a,b,c,d){try{var e=JSON.parse(a);return"/gp/aq-feedback/lazyLoad/handler/af-link-handler.html?pl="+
encodeURIComponent(JSON.stringify({adCreativeMetaData:{adCreativeId:e[0],adId:b,campaignId:c,adImpressionId:e[1],adNetwork:"aax",adProgramId:1010},adPlacementMetaData:{adElementId:e[2],pageType:e[3],pageUrl:e[4],searchTerms:e[5],slotName:d}}))}catch(q){return null}},ia=function(){var a=g("data-ad-feedback");if(a){var b=g("data-slot"),c=g("data-aid"),d=g("data-cid");a=ha(a,c,d,b);fa({url:a,onSuccess:function(a){var b=a.html,c=f('[data-id="afb-content"]');c&&b&&(c.innerHTML=b);if(a=a.script)b=f().ownerDocument.createElement("script"),
b.type="text/javascript",b.innerHTML=a,f().appendChild(b);p.log("AdFeedbackSuccess")},onError:function(){var a=f('[data-id="afb-fallback"]');a&&(a.style.display="block");p.log("AdFeedbackFallback")}})}},E=function(){l('[data-id="cta"]').forEach(function(a){if(a.parentElement){var b=f('[data-id*="cta-fallback"]',a.parentElement),c=f(".a-truncate",a),d=f(".a-truncate-full",a);c&&d&&(d.clientHeight>c.clientHeight&&b?(b.style.display="block",a.parentElement.removeChild(a)):(b=a.parentElement.getAttribute("aria-hidden"),
b&&"false"!==b||(b=a.getAttribute("data-label")||d.innerHTML,a.parentElement.setAttribute("aria-label",b)),(c=f('[data-id*="cta-chevron"]',a))&&!d.hasAttribute("data-chevron")&&(d.setAttribute("data-chevron","true"),a=d.innerHTML.split(" "),b=a.pop(),c=c.innerHTML,d.innerHTML="<span>"+a.join(" ")+' </span><span style="white-space:pre">'+b+"&nbsp;"+c+"</span>")))}})},ja=function(a){var b=g("data-src",a)||"",c=g("data-srcset",a)||"",d=a.cloneNode();d.removeAttribute("data-src");d.removeAttribute("data-srcset");
d.removeAttribute("data-lazy");d.srcset=c;d.src=b;a.parentNode&&a.parentNode.insertBefore(d,a);d.onload=function(){a.style.opacity="0";p.log("LazyLoaded")}};u=function(a){return function(){return r.__awaiter(void 0,void 0,void 0,function(){return r.__generator(this,function(b){switch(b.label){case 0:return p.log("Loaded"),[4,P["default"].pageReady];case 1:b.sent();p.log("Ready");try{var c=f(".sbx-no-js",void 0);c&&c.classList.remove("sbx-no-js");try{var d=Z({anonymizedRequestId:g("data-rid"),campaignId:g("data-cid"),
slotName:g("data-slot")});d.i({asins:[].map.call(l("[data-asin]"),X),creativeType:(g("data-card-metrics-id")||"").split("_")[0]||null,creativeVariation:g("data-var"),market:g("data-mrkt"),version:g("data-ts"),viewport:S(),weblabs:R()});W(d);ea(d);da(d);ba(d)}catch(e){m(e,"nori")}try{E(),B("resize",E,void 0)}catch(e){m(e,"cta")}try{l('img[data-lazy="true"]').forEach(ja)}catch(e){m(e,"lazyload")}if(a&&a.onLoad)a.onLoad()}catch(e){m(e,"client")}return[2]}})})}}({onLoad:function(){ia()}});x._operationNames=
[];x.card=u});
