'use strict';mix_d("SBXGwentCards__multi-brand-creative-desktop:multi-brand-creative-desktop__R3bC0Xma","exports tslib @c/dom @c/metrics @c/logger @c/aui-feature-detect @c/aui-utils @p/a-ajax @c/pagemarker".split(" "),function(D,w,z,S,T,U,V,W,X){function n(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var A=n(z),E=n(S),Y=n(T),Z=n(U),F=n(V),aa=n(W),ba=n(X),h,ca=(h={},h.e="basebe.ClientErrors.4",h.i="basebe.Impressions.5",h.c="basebe.Clicks.4",h.s="basebe.Swipes.4",h.v="basebe.Viewabilities.4",
h.vc="basebe.VisualCompleteness.6",h),G=function(a,b){return"matches"in a?a.matches(b):"msMatchesSelector"in a?a.msMatchesSelector(b):"webkitMatchesSelector"in a?a.webkitMatchesSelector(b):0<=u(b,k().body).indexOf(a)},g=function(a,b){b=b||A["default"].cardRoot;return!a||G(b,a)?b:b.querySelector(a)},u=function(a,b){return Array.prototype.slice.call((b||A["default"].cardRoot).querySelectorAll(a))},f=function(a,b){return(b=g("["+a+"]",b))?b.getAttribute(a):null},B=function(a,b){for(;b&&b!==A["default"].cardRoot;){if(G(b,
a))return b;b=b.parentElement}return null},H=function(a,b){return(b=B("["+a+"]",b))?b.getAttribute(a):null},I=function(a){if(a)return a=a.getBoundingClientRect(),{left:a.left,right:a.right,top:a.top,bottom:a.bottom};a=k().defaultView;return{left:0,top:0,right:a.innerWidth,bottom:a.innerHeight}},k=function(){return g().ownerDocument},da=function(){var a=f("data-wl");return a?a.split(","):[]},ea=function(){var a=k().defaultView;return a.innerWidth+"x"+a.innerHeight},p=function(a,b){Y["default"].log(a,
"ERROR",b||"unknown")},fa=function(a,b){var c,d=/\?([^#]+)/.exec(b.href);if(d){d=d[1].split("&");var e=null;try{for(var r=w.__values(d),x=r.next();!x.done;x=r.next()){var m=x.value;if(0===m.indexOf("ref_=")){e=m;break}}}catch(v){var f={error:v}}finally{try{x&&!x.done&&(c=r.return)&&c.call(r)}finally{if(f)throw f.error;}}f=e?(f=e.split("=").pop()||"")?f.split("_"):[]:[]}else f=[];c={};if(5<f.length){c.el=f.pop()||null;a:{var g;try{for(var l=w.__values(f),q=l.next();!q.done;q=l.next()){var t=q.value;
if(/^\d+$/.test(t)){var k=t;break a}}}catch(v){var h={error:v}}finally{try{q&&!q.done&&(g=l.return)&&g.call(l)}finally{if(h)throw h.error;}}k=null}c.index=k;c.asin=H("data-asin",b);c.type=H("data-avar",b)}a.c(c,b)},ha=function(a,b){var c=k().defaultView,d=function(e){2!==e.button&&(fa(a,b),e.metaKey||e.altKey||e.shiftKey||e.ctrlKey||1===e.button||"_blank"===b.target||(e.preventDefault(),c.setTimeout(function(){c.open(b.href,b.target||"_top")},50)))};b.addEventListener("click",d);b.addEventListener("auxclick",
d)},ia=function(a){u("[href]").forEach(function(b){ha(a,b)})},ja=function(a){return{id:f("data-asin",a),prime:!!g(".a-icon-prime",a),price:!!g(".a-price",a),savings:!!g('.a-price[data-a-strike="true"]',a),rating:f("data-rt",a),badge:f("data-deal",a)}},ka=function(a,b){if(b)for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);return a},la=function(a){var b=a.anonymizedRequestId,c=a.campaignId,d=a.slotName,e=function(a,e){try{E["default"].event(ka({anonymizedRequestId:b,campaignId:c,
slotName:d},e),"base-be",ca[a],{ssd:!0})}catch(m){p(m,"event:"+(a||"?"))}};return{i:e.bind(null,"i"),v:e.bind(null,"v"),vc:e.bind(null,"vc"),c:e.bind(null,"c"),s:e.bind(null,"s"),e:function(a){e("e",a&&{name:a.name,message:a.message,stack:a.stack})}}},ma=function(a,b){var c=null,d=null;a.addEventListener("touchstart",function(a){c=a.touches[0].pageX});a.addEventListener("touchmove",function(a){null===c&&(c=a.touches[0].pageX);d=a.touches[0].pageX});a.addEventListener("touchend",function(){null!==
c&&null!==d&&b(d-c);c=d=null})},na=function(a){if(Z["default"].isSupported("touch")){var b=function(b){var c=Math.abs(b);30<c&&a.s({direction:0>b?"left":"right",length:c})};u("[data-track-swipe]").forEach(function(a){return ma(a,b)})}},oa=function(a,b){var c=k().defaultView,d,e=function(){d||(d=c.setTimeout(a,b))};e.cancel=function(){c.clearTimeout(d);d=0};return e},pa=function(a,b){void 0===b&&(b=0);return function(){F["default"].delay(a,b)}},J=function(a,b,c){var d=(c||{}).ms||25,e=(c||{}).el||
k().defaultView,f=F["default"].throttle(b,d);e.addEventListener(a,f);return function(){e.removeEventListener(a,f)}},C=function(a,b){return J("resize",a,b)},K=function(a,b){return J("scroll",a,b)},L=function(a,b,c){return 0<=a?Math.min(c-a,b-a):0<b?Math.min(Math.min(b,c),b-a):0},qa=function(a,b){var c=function(){var a=b?b:g(),c=d,e=a.getBoundingClientRect();if(a=e.width*e.height){var f=e.top,h=e.bottom,l=e.left,q=e.right,t=k().defaultView;e=t.innerHeight;l=L(l,q,t.innerWidth);f=L(f,h,e);.5<=l*f/a?
c():c.cancel()}},d=oa(function(){e();a.v(null,b)},1E3),e=K(c);c()},ra=function(a){var b=Date.now(),c=u("img"),d=c.length,e=0,r=function(){++e===d&&a.vc({delay:Date.now()-b})};c.forEach(function(a){null!==f("data-lazy",a)&&null!==f("data-src",a)?a.addEventListener("load",function(){a.src===a.dataset.src&&r()}):a.complete?r():a.addEventListener("load",r)})},M=function(a,b){void 0===b&&(b=1);E["default"].count("sbxGwentClient"+a,b)},y={log:function(a){var b=k().defaultView;var c=f("data-iid");(b=c&&
b.sbxGwentClient&&"number"===typeof b.sbxGwentClient[c]?Date.now()-b.sbxGwentClient[c]:null)?M(a,b):M("NoPageTime")}},sa=function(a){var b=a.url,c=a.onSuccess,d=a.onError;b||d();aa["default"].get(b,{success:function(a){a&&"ok"===a.status?c(a):d()},error:d,abort:d})},ta=function(a,b,c,d){try{var e=JSON.parse(a);return"/gp/aq-feedback/lazyLoad/handler/af-link-handler.html?pl="+encodeURIComponent(JSON.stringify({adCreativeMetaData:{adCreativeId:e[0],adId:b,campaignId:c,adImpressionId:e[1],adNetwork:"aax",
adProgramId:1010},adPlacementMetaData:{adElementId:e[2],pageType:e[3],pageUrl:e[4],searchTerms:e[5],slotName:d}}))}catch(r){return null}},ua=function(){var a=f("data-ad-feedback");if(a){var b=f("data-slot"),c=f("data-aid"),d=f("data-cid");a=ta(a,c,d,b);sa({url:a,onSuccess:function(a){var b=a.html,c=g('[data-id="afb-content"]');c&&b&&(c.innerHTML=b);if(a=a.script)b=k().createElement("script"),b.type="text/javascript",b.innerHTML=a,g().appendChild(b);y.log("AdFeedbackSuccess")},onError:function(){var a=
g('[data-id="afb-fallback"]');a&&(a.style.display="block");y.log("AdFeedbackFallback")}})}},N=function(){u('[data-id="cta"]').forEach(function(a){if(a.parentElement){var b=g('[data-id*="cta-fallback"]',a.parentElement),c=g(".a-truncate",a),d=g(".a-truncate-full",a);c&&d&&(d.clientHeight>c.clientHeight&&b?(b.style.display="block",a.parentElement.removeChild(a)):(b=a.parentElement.getAttribute("aria-hidden"),b&&"false"!==b||(b=a.getAttribute("data-label")||d.innerHTML,a.parentElement.setAttribute("aria-label",
b)),(c=g('[data-id*="cta-chevron"]',a))&&!d.hasAttribute("data-chevron")&&(d.setAttribute("data-chevron","true"),a=d.innerHTML.split(" "),b=a.pop(),c=c.innerHTML,d.innerHTML="<span>"+a.join(" ")+' </span><span style="white-space:pre">'+b+"&nbsp;"+c+"</span>")))}})},va=function(a){var b=f("data-src",a)||"",c=f("data-srcset",a)||"",d=a.cloneNode();d.removeAttribute("data-src");d.removeAttribute("data-srcset");d.removeAttribute("data-lazy");d.srcset=c;d.src=b;a.parentNode&&a.parentNode.insertBefore(d,
a);d.onload=function(){a.style.opacity="0";y.log("LazyLoaded")}},xa=function(a,b){return function(){var c,d=u("[data-pixel]"),e=0;try{for(var f=w.__values(d),g=f.next();!g.done;g=f.next()){var m=g.value,h=a,k=I(m),l=I(h),q=k.left,t;if(!(t=q>=l.left&&q<=l.right)){var n=k.right;t=n>=l.left&&n<=l.right}if(t){var p=m.getAttribute("data-pixel");p&&p.length&&((new Image).src=p);m.removeAttribute("data-pixel");++e}}}catch(wa){var v={error:wa}}finally{try{g&&!g.done&&(c=f.return)&&c.call(f)}finally{if(v)throw v.error;
}}e===d.length&&b()}},ya=function(a,b){var c=xa(a,function(){d();e();"function"===typeof b&&b()}),d=K(c,{el:a}),e=C(c);c();return c},O=function(){},P=function(a){a.setAttribute("disabled","disabled");if(a=B(".a-button",a))a.classList.add("a-button-disabled"),a.classList.remove("a-button-focus")},Q=function(a){a.removeAttribute("disabled");(a=B(".a-button",a))&&a.classList.remove("a-button-disabled")},R=function(a,b){var c=pa(b,350);a.addEventListener("click",c);return function(){a.removeEventListener("click",
c)}},za=function(a,b){var c=g('[data-id="track"]'),d=g('[data-button="prev"]'),e=g('[data-button="next"]');if(!c||!d||!e)return O;var f=!!k().querySelector('[dir="rtl"]'),h=0,m=0,n=function(a){c.children&&c.children[0]&&(h=parseInt(window.getComputedStyle(c.children[0]).width,10));c.style.transform="translateX("+(f?"":"-")+a*(h+24)+"px)"};a=function(a){var b="next"===a?1:-1;return function(){m+=b;Q(d);Q(e);m===c.children.length-2&&P(e);0===m&&P(d);n(m)}};C(function(){return n(m)});e.addEventListener("click",
a("next"));d.addEventListener("click",a("prev"));var p=R(e,b),l=R(d,b);return function(){p();l()}};z=function(a){return function(){return w.__awaiter(void 0,void 0,void 0,function(){return w.__generator(this,function(b){switch(b.label){case 0:return y.log("Loaded"),[4,ba["default"].pageReady];case 1:b.sent();y.log("Ready");try{var c=g(".sbx-no-js",void 0);c&&c.classList.remove("sbx-no-js");try{var d=la({anonymizedRequestId:f("data-rid"),campaignId:f("data-cid"),slotName:f("data-slot")});d.i({asins:[].map.call(u("[data-asin]"),
ja),creativeType:(f("data-card-metrics-id")||"").split("_")[0]||null,creativeVariation:f("data-var"),market:f("data-mrkt"),version:f("data-ts"),viewport:ea(),weblabs:da()});ia(d);ra(d);qa(d);na(d)}catch(e){p(e,"nori")}try{N(),C(N)}catch(e){p(e,"cta")}try{u('img[data-lazy="true"]').forEach(va)}catch(e){p(e,"lazyload")}if(a&&a.onLoad)a.onLoad()}catch(e){p(e,"client")}return[2]}})})}}({onLoad:function(){ua();var a=g('[data-id="carousel"]');if(a){var b=O,c=ya(a,function(){b()});g('[data-enhanced-mbc="true"]')&&
(b=za(a,c))}}});D._operationNames=[];D.card=z});
