'use strict';mix_d("MorpheusPopularityRankSidesheetCards__morpheus-popularity-rank-sidesheet-card:morpheus-popularity-rank-sidesheet-card__GZg9hvse","exports tslib @c/browser-operations @c/logger @c/metrics @c/scoped-dom @p/monarch-sidesheet @c/remote-operations".split(" "),function(z,u,G,H,k,I,J,K){function q(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var L=q(G),t=q(H),g=q(I),n=q(J),A=q(K),v;(function(a){a.asinItemClickMetricReportHandler="asinItemClickMetricReportHandler";a.aodLinkClickHandler=
"aodLinkClickHandler"})(v||(v={}));var B=v,w=function(a){var b=0,e=setInterval(function(){5<b&&clearInterval(e);b++;var c=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_header__1CUj_")[0],d=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_alert-message__3I7G9")[0];if(c||d)clearInterval(e),a.focus()},500)},C=function(a){var b=0,e=setInterval(function(){5<b&&clearInterval(e);b++;var c=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_item_link__1pKM-")[0];
c&&(clearInterval(e),c.focus())},500)},D=function(a){var b=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_err-view__V9B13")[0];a&&b&&(a.innerHTML=b.innerHTML)},m=function(a){a&&(a.style.display="none")},M=function(a){var b=new Map([["kindle_meta_binding","Kin"],["audiobooks_digital_meta_binding","Aud"],["hardcover_meta_binding","Hrd"],["paperback_meta_binding","Pap"],["mass_market_paperback_meta_binding","Mmp"],["audiobooks_meta_binding","Abk"]]);return b.has(a)?
"morpheusSidesheetTabClicked"+b.get(a):"morpheusSidesheetTabClickedOther"},r,P=function(a){a.preventDefault();var b=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_sidesheet__R6-h1")[0],e=g["default"].cardRoot.getElementsByClassName("landingAsinValue")[0];if(b&&e){a=g["default"].cardRoot.getElementsByClassName("sidesheetMainBody")[0];!r&&a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_alert-message__3I7G9")[0]&&n["default"].setContent("");
var c=Date.now();k.count("seeAllFormatsExpanderClicked",1);n["default"].show();if(r)w(b);else{var d=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_content-ctr__jbXAx")[0],x=function(){n["default"].setContent(d.innerHTML);N(b);O(b);var a=L["default"].setup().define;a(B.asinItemClickMetricReportHandler,"click",function(b){var a,e,f=b.target.parentElement;b="true"===(null===(a=null===f||void 0===f?void 0:f.dataset)||void 0===a?void 0:a.newRelease);a="true"===
(null===(e=null===f||void 0===f?void 0:f.dataset)||void 0===e?void 0:e.popularityEnabled);b&&k.count(a?"morpheusNewReleasedItemClickedWithBadge":"morpheusNewReleasedItemClickedNoBadge",1);k.count("morpheusEditionItemClicked",1)});a(B.aodLinkClickHandler,"click",function(a){var b;a=a.target;a.classList.contains("morpheusAodEntryLink")&&!a.classList.contains("morpheusAodDeclarativeAction")&&(n["default"].closeSidesheet(a.id),a=null===(b=a.parentElement)||void 0===b?void 0:b.getElementsByClassName("morpheusAodDeclarativeAction")[0])&&
(a.click(),k.count("morpheusAODClicked",1))});a=b.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_tab-content__37vVR");for(var h=0;h<a.length;h++)a[h].getElementsByClassName("sidesheetAsinListContainer")[0]&&F(e.value,a[h]);a=Date.now()-c;k.count("morpheusSidesheetContentLoadLatency",a);r=!0};A["default"].setup().getSidesheetHtml({asin:e.value}).then(function(a){d&&(d.innerHTML=a.outerHTML,x(),w(b))}).catch(function(a){D(d);n["default"].setContent(d.innerHTML);r=!1;k.count("failedRenderSidesheetContent",
1);w(b);t["default"].log("Experiencing some issues to load sidesheet view for ASIN "+e.value+", trace: "+a,"ERROR")})}}else t["default"].log("Not able to open see all formats sidesheet, missing neccessary component.","FATAL")},y=function(a,b,e,c){var d=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_tab-content-spinner__3lJtW")[0],x=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_alert-message__3I7G9")[0],l=a.getElementsByClassName("sidesheetAsinListContainer")[0];
m(l);m(x);d&&(d.style.display="inline-block");A["default"].setup().getMetabindingTabContentHtml({asin:b,totalPageNumber:e,currentPageNumber:c?c:1}).then(function(c){a.innerHTML=c.innerHTML;F(b,a,e);C(a)}).catch(function(b){D(a);m(d);a.innerHTML+=d.outerHTML;k.count("failedRenderMetabindingTabContent",1);t["default"].log("Experiencing some issues to load tab content view, trace: "+b,"ERROR")})},N=function(a){for(var b=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_tab-item__2zc-Z"),
e=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_tab-content__37vVR"),c=function(c){var d=e[c].getElementsByClassName("a-box-inner")[0];d&&(d.style.padding="0");b[c].addEventListener("click",function(){var d=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_active__3v2zd")[0];if(d!==b[c]){var f=b[c].getElementsByClassName("metabindingSymbol")[0];f&&f.value&&k.count(M(f.value),1);b[c].className="_morpheus-popularity-rank-sidesheet-card_ss_tab-item__2zc-Z _morpheus-popularity-rank-sidesheet-card_ss_active__3v2zd";
d.className="_morpheus-popularity-rank-sidesheet-card_ss_tab-item__2zc-Z";d=e[c];if((f=d.getElementsByClassName("sidesheetAsinListContainer")[0])&&"none"!==f.style.display)C(d);else{f=b[c].getElementsByClassName("winningAsin")[0];var g=b[c].getElementsByClassName("totalPages")[0];y(d,f.value,Number(g.value))}}})},d=0;d<b.length;d++)c(d)},O=function(a){var b=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_tab-row__1Uxai")[0],e=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_scroll-back__2cqlo")[0],
c=a.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_scroll-forw__2NDFi")[0];if(e&&c&&b){var d=e.offsetLeft>c.offsetLeft;d&&(e.classList.remove("_morpheus-popularity-rank-sidesheet-card_ss_scroll-back-radius__2TGra"),c.classList.remove("_morpheus-popularity-rank-sidesheet-card_ss_scroll-forw-radius__3O1Mg"));var g=!1,l=d&&3<b.scrollLeft,h;m(e);var f=function(){return l?3>=Math.abs(b.scrollLeft):3>=b.scrollWidth-Math.abs(b.scrollLeft)-b.offsetWidth},E=function(){return l?3>=b.scrollWidth-
Math.abs(b.scrollLeft)-b.offsetWidth:3>=Math.abs(b.scrollLeft)};f()&&m(c);b.addEventListener("scroll",function(){f()&&"none"!==c.style.display?(m(c),clearInterval(h)):!f()&&"none"===c.style.display&&c&&(c.style.display="inline-block");E()&&"none"!==e.style.display?(m(e),clearInterval(h)):!E()&&"none"===e.style.display&&e&&(e.style.display="inline-block")});c.addEventListener("mousedown",function(){h=setInterval(function(){var a=b.scrollLeft;d&&!g?b.scrollLeft-=3:b.scrollLeft+=3;d&&!g&&0===a&&0===
b.scrollLeft&&(g=!0,b.scrollLeft+=3)},10)});c.addEventListener("mouseup",function(){clearInterval(h)});e.addEventListener("mousedown",function(){h=setInterval(function(){d&&!g?b.scrollLeft+=3:b.scrollLeft-=3},10)});e.addEventListener("mouseup",function(){clearInterval(h)})}},F=function(a,b,e){for(var c=b.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ss_pagination__4GE1X")[0],d=b.getElementsByClassName("a-pagination")[0].getElementsByTagName("li"),g=function(g){var f=d[g];f.classList.contains("a-disabled")||
f.addEventListener("click",function(h){h.preventDefault();h=f&&f.classList.contains("a-selected");var p;0===g&&c.dataset.prevPageNumber?p=Number(c.dataset.prevPageNumber):g===d.length-1&&c.dataset.nextPageNumber?p=Number(c.dataset.nextPageNumber):f&&f.dataset.pageNumber&&(p=Number(f.dataset.pageNumber));f&&!h&&p&&(k.count("morpheusSidesheetOtherPageNavigated",1),e?y(b,a,e,p):(h=d[d.length-2])&&h.dataset.pageNumber&&y(b,a,Number(h.dataset.pageNumber),p))})},l=0;l<d.length;l++)g(l)};z._operationNames=
["getSidesheetHtml","getMetabindingTabContentHtml"];z.card=function(){return u.__awaiter(void 0,void 0,void 0,function(){var a,b,e,c,d,k,l,h,f;return u.__generator(this,function(m){a=g["default"].cardRoot.getElementsByClassName("morpheusRoot")[0];if(!a)return[2];e=(b=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_saf__39PV9")[0])?b:g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_saf-link__2TS-U")[0];c=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_sidesheet__R6-h1")[0];
d=g["default"].cardRoot.getElementsByClassName("sidesheetMainBody")[0];k=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_overlay__T88OB")[0];l=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_spinner__VHgKZ")[0];h=g["default"].cardRoot.getElementsByClassName("_morpheus-popularity-rank-sidesheet-card_ingress_sidesheet-close__13oI1")[0];f=[c,d,k,l,h];if(f.every(function(a){return a})&&f.map(function(a){return a.id}).every(function(a){return a}))n["default"].initialize.apply(n["default"],
u.__spread(f.map(function(a){return a.id}))),h.tabIndex=0;else return t["default"].log("Not able to initialize see all formats sidesheet, missing neccessary component or component id.","FATAL"),[2];r=!1;e&&e.addEventListener("click",P);return[2]})})}});
