'use strict';mix_d("SimilaritiesUICards__p13n-desktop-sims-fbt:p13n-desktop-sims-fbt__6givgmd0",["exports","tslib","@c/browser-operations","@c/remote-operations","@c/scoped-dom"],function(t,u,w,x,y){function m(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var z=m(w),A=m(x),g=m(y),v=function(a){var b=g["default"].cardRoot.getElementsByClassName("cardRoot")[0];var c=1;b&&b.dataset.count&&(c=Number(b.dataset.count));var d;b&&b.dataset.components&&(d=JSON.parse(b.dataset.components));
var n;b&&b.dataset.addToCart&&(n=JSON.parse(b.dataset.addToCart));var h;b&&b.dataset.priceTotals&&(h=JSON.parse(b.dataset.priceTotals));if(d&&h){b=d;d=c;for(var k=[],e=[],f=0;f<d;f++){var p=f+1;1<p&&(k[f]=g["default"].cardRoot.getElementsByClassName("thumbnailPlus-"+String(p))[0]);e[f]=g["default"].cardRoot.getElementsByClassName("thumbnail-"+String(p))[0]}var l=!1,m=0;c="";for(f=0;f<d;f++){p=String(f+1);var q=k[f],r=e[f];b[p]&&b[p].checked?(m++,c+=p,0===f?l=!0:q&&(l?q.style.display="unset":(l=!0,
q.style.display="none")),r&&(r.style.display="unset")):(q&&(q.style.display="none"),r&&(r.style.display="none"))}b=m;h=h[c];c=g["default"].cardRoot.getElementsByClassName(a.totalLabel)[0];d=g["default"].cardRoot.getElementsByClassName(a.totalAmount)[0];k=g["default"].cardRoot.getElementsByClassName(a.addItems)[0];e=g["default"].cardRoot.getElementsByClassName(a.chooseItems)[0];f=g["default"].cardRoot.getElementsByClassName(a.actionDetails)[0];0===b?(k&&(k.style.display="none"),c&&(c.style.display=
"none"),e&&(e.style.display="unset"),f&&(f.style.visibility="hidden")):(h?(c&&d&&(d.innerText=h,c.style.display="block"),k&&(k.style.display="none"),e&&(e.style.display="none")):(k&&(k.style.display="inline-block"),e&&(e.style.display="none"),c&&(c.style.display="none")),f&&(f.style.visibility="visible"));a=g["default"].cardRoot.getElementsByClassName(a.addAllButton)[0];h=void 0;a&&(h=a.getElementsByClassName("a-button-text")[0]);0===b?a&&!a.classList.contains("a-button-disabled")&&a.classList.add("a-button-disabled"):
(a&&a.classList.contains("a-button-disabled")&&a.classList.remove("a-button-disabled"),h&&n&&n.length>=b&&(h.innerText=n[b-1]))}},l;(function(a){a.clickHandler="clickHandler";a.checkHandler="checkHandler";a.popupHandler="popupHandler"})(l||(l={}));var d={simsFbtContainter:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-containter__2Cffh",thumbnailBox:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-box__4jnIT",thumbnailPlus:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-plus__zdWox",productBox:"_p13n-desktop-sims-fbt_fbt-desktop_product-box__3PBxY",
itemDetailsPerAsin:"_p13n-desktop-sims-fbt_fbt-desktop_item-details-per-asin__3DtF1",fbtItemCheck:"_p13n-desktop-sims-fbt_fbt-desktop_fbt-item-check__pUIoy",addAllButton:"_p13n-desktop-sims-fbt_fbt-desktop_add-all-button__1TRXG",totalLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-label__dI983",addItems:"_p13n-desktop-sims-fbt_fbt-desktop_add-items__16weX",chooseItems:"_p13n-desktop-sims-fbt_fbt-desktop_choose-items__15UQx",totalAmount:"_p13n-desktop-sims-fbt_fbt-desktop_total-amount__wLVdU",priceAddToCartBox:"_p13n-desktop-sims-fbt_fbt-desktop_price-add-to-cart-box__3OUdK",
shipMessageBox:"_p13n-desktop-sims-fbt_fbt-desktop_ship-message-box__t-OOr",shippingInfoShowBox:"_p13n-desktop-sims-fbt_fbt-desktop_shipping-info-show-box__17yWM",showDetailsBox:"_p13n-desktop-sims-fbt_fbt-desktop_show-details-box__-R3Xb",showDetails:"_p13n-desktop-sims-fbt_fbt-desktop_show-details__3GnPL",hideDetails:"_p13n-desktop-sims-fbt_fbt-desktop_hide-details__28l17",simsFbtUnselectedItem:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-unselected-item__VQmZx",simsFbtRows:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-rows__2LJXs",
bucketDivider:"_p13n-desktop-sims-fbt_fbt-desktop_bucket-divider__25poP",titleTruncate:"_p13n-desktop-sims-fbt_fbt-desktop_title-truncate__1pPAM",detailRowElement:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element__2WDgq",minQuantity:"_p13n-desktop-sims-fbt_fbt-desktop_min-quantity__1j2Bo",actionDetails:"_p13n-desktop-sims-fbt_fbt-desktop_action-details__18ZiI"};t._operationNames=["getValueNoParams"];t.card=function(){return u.__awaiter(void 0,void 0,void 0,function(){var a,b,c;return u.__generator(this,
function(m){a=z["default"].setup().define;b=A["default"].setup();b.getValueNoParams();if(!g["default"].cardRoot)return[2];v(d);c=!0;a(l.clickHandler,"click",function(a){a=g["default"].cardRoot.getElementsByClassName(d.shippingInfoShowBox);var b=g["default"].cardRoot.getElementsByClassName(d.showDetails)[0],n=g["default"].cardRoot.getElementsByClassName(d.hideDetails)[0];b&&(c?(b.style.display="none",n.style.display="unset",[].forEach.call(a,function(a,b){a.style.display="block";c=!1})):(b.style.display=
"unset",n.style.display="none",[].forEach.call(a,function(a,b){a.style.display="none"}),c=!0))});a(l.checkHandler,"click",function(a){a=a.event.target;if(!a||"fbtCheck"===a.id.substr(0,8)){for(;a&&!a.classList.contains(d.fbtItemCheck);)a=a.parentElement;if(a){var b=a.id,c=g["default"].cardRoot.getElementsByClassName("cardRoot")[0],e=void 0;c&&c.dataset.components&&(e=JSON.parse(c.dataset.components));e&&e[b]&&(e[b].checked=!e[b].checked);e&&e[b].checked&&(a.classList.contains(d.simsFbtUnselectedItem)&&
a.classList.remove(d.simsFbtUnselectedItem),a.classList.contains(d.fbtCheckDetails)||a.classList.add(d.fbtCheckDetails));e&&!e[b].checked&&(a.classList.remove(d.fbtCheckDetails),a.classList.add(d.simsFbtUnselectedItem));c.dataset.components=JSON.stringify(e);v(d)}}});return[2]})})}});
