'use strict';mix_d("P13NSCCards__p13n-rvi:p13n-rvi__uUmSPnG7","exports tslib @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/A @p/a-carousel-framework @c/aui-modal @c/aui-untrusted-ajax @c/browser-operations @c/logger @c/aui-utils".split(" "),function(q,l,x,y,z,A,B,C,D,E,F,G,U){function f(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var H=f(x),I=f(z),g=f(A),m=f(B),J=f(C),K=f(D),L=f(E),r=f(F),n=f(G),N=function(a){return l.__awaiter(void 0,void 0,void 0,function(){var c,
b,d,e,k;return l.__generator(this,function(h){c=g["default"].cardRoot.querySelector(".report-problem-modal-root");if(!c)return[2];b={a11yOpenMessage:"A modal for internal users to report problems with recommendations",hideHeader:!1};d=K["default"].create("report-flag-modal",".report-problem-modal-root",b);e=r["default"].setup();k=g["default"].cardRoot.querySelector(".report-flag");e.define("show","click",function(){d.show()});e.attach("show",k);M(a);return[2]})})},M=function(a){var c=g["default"].cardRoot.querySelector(".report-flag"),
b=r["default"].setup();b.define("showFlag","mouseover",function(){c.classList.remove("report-flag-hide")});b.define("hideFlag","mouseout",function(){c.classList.add("report-flag-hide")});b.attach("showFlag",a);b.attach("hideFlag",a);var d=g["default"].cardRoot.querySelector(".internal-flag-form");d.onsubmit=function(c){return O(d,c,a)}},O=function(a,c,b){c.preventDefault();c=a.querySelector(".internal-flag-env-data").dataset;var d=a.querySelector(".internal-flag-dropdown").innerText,e=a.querySelector(".internal-flag-textarea");
a=e.firstElementChild.value;var k=g["default"].cardRoot.querySelectorAll(".a-carousel-card"),h=P(b,k.length);b="Internal user reported issue with your widget: "+g["default"].cardRoot.querySelector(".a-carousel-heading").innerText;c=Q(k,h,d,a,c);L["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:"1b027359-e4c6-4e3c-92a8-0ff8a2ecb593",description:c,descriptionContentType:"text/amz-markdown-sim",
title:b}}).then(function(a){u(e,!0,a)}).catch(function(a){u(e,!1,a)});return!1},P=function(a,c){if(!a.dataset.aCarouselOptions)return n["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=g["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(a){return JSON.parse(a).id}).slice(b,b+c)},Q=function(a,c,b,d,e){for(var k="",h=0;h<a.length;h++){var t=
a[h].querySelector(".a-dynamic-image");k+=(t?"![]("+t.src+")":"IMAGE MISSING")+"\nASIN: "+(c[h]?c[h]:"ASIN MISSING")+"\n\n"}return"**This SIM issue is created by the 'Report a Problem' internal tool. To know more, here's its wiki:https://w.amazon.com/bin/view/CoreRecommendations/Internships/annchn/Report-a-Problem-UX-on-P13NWidgets-DesignDoc/**\n\n**Problem:** "+(b+"\n**CTI:** "+e.cti+" \n**CustomerID:** "+e.customerId+"\n**Device Type:** "+e.deviceType+"\n**Facets:** ")+(e.facets+"\n**MarketplaceID:** "+
e.marketplaceId+"\n**Content Reftag:** "+e.reftTag+"\n**SessionID:** ")+(e.sessionId+"\n**Strategy ID:** "+e.strategyId+(""!==d?"\n**Comment:** "+d:"")+"\n**List of ASINs:**\n\n"+k)},u=function(a,c,b){var d=a.nextSibling;d&&d.classList.contains("report-problem-message")||(d=document.createElement("h5"),d.classList.add("report-problem-message"),a.after(d));c?(d.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?d.innerText=
"Success, here's the SIM issue you created: https://issues.amazon.com/issues/"+b.responseBody.response.id:(n["default"].log("Fail to find the id of the SIM issue created in the response body of response data.","ERROR"),d.innerText="Success, but we could not find the link to the SIM."):(n["default"].log("The response body of response data is not an object.","ERROR"),d.innerText="Success, but we could not find the link to the SIM.")):(d.classList.add("a-color-error"),d.innerText="Oops! Something went wrong. Please try again.")},
v=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,w=/[^\/\-\[\]():\s]/,R=function(a){var c=m["default"].$("<div>")[0];c.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||"2",10),d=function(){var c=a.innerHTML;a.innerHTML="&hellip;";var b=a.clientHeight;a.innerHTML=c;return b}();if(b){if(d){var e=function(a){c.innerHTML=a;return Math.round(c.clientHeight/
d)<=b},k=function(b,d){b=b.split(d);var e=Math.floor(a.clientWidth/12),h=function(b){c.classList.add("p13n-sc-offscreen-truncate");c.style.overflow="hidden";c.textContent=b;a.appendChild(c);b=a.clientWidth>=a.scrollWidth;a.removeChild(c);return b},k=function(a){var c=a.length-e;a.trim().length>e&&!h(a)&&Array.prototype.slice.call(a).map(function(a,b){return b>e&&b<=c&&w.test(a)?"&shy;"+a:a});return a};return b.map(function(a){return k(a)}).join("")};return{truncate:function(){var b=a.innerHTML.trim(),
d=a.textContent||"";b=k(b,v);a.appendChild(c);if(e(b))a.removeChild(c),a.innerHTML=b;else{var g=b.split(v);for(var f=1,l=g.length,m,q,p=0;f!==l;)if(m=Math.floor((l+f)/2),q=g.slice(0,m).join("")+"&hellip;",e(q)){if(1>=l-m){for(p=m;0<p&&!w.test(g[p-1]);)p--;break}f=m}else l=m;g=0===p?void 0:g.slice(0,p).join("")+"&hellip;";g?(a.innerHTML=g,a.setAttribute("title",d)):(n["default"].log("Unable to successfully truncate line "+b,"ERROR"),a.removeChild(c))}}}}n["default"].log("Truncation element does not have a line height or it is zero",
"ERROR")}else n["default"].log("Truncation element missing necessary line number data","ERROR")},S=function(a){a=a.getElementsByClassName("p13n-sc-truncate");Array.prototype.slice.call(a).map(function(a){var b=R(a);b&&(b.truncate(),a.classList.add("p13n-sc-truncated"),a.classList.remove("p13n-sc-truncate"),a.className=a.className.replace(/p13n-sc-line-clamp-\d/g,""))})},T={initCarousel:function(a){return l.__awaiter(void 0,void 0,void 0,function(){var c,b,d,e,k,h,f;return l.__generator(this,function(n){switch(n.label){case 0:c=
g["default"].cardRoot.classList.contains("p13n-sc-shoveler")?g["default"].cardRoot:g["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler")[0];b=I["default"].setup(["getCarouselItems"]);if(!c)return[2];d=J["default"].getCarousel(y.unscope(c));e=H["default"].getCarousel(c);k=c.dataset||{};h=d.getAttr("name");f=function(){m["default"].loadDynamicImage("[data-name]='"+h+"' .p13n-sc-dynamic-image");S(c);null===a||void 0===a?void 0:a(c)};return[4,e.initialized];case 1:return n.sent(),N(c),m["default"].on("a:carousel:"+
h+":change:pageSize",f),m["default"].on("a:carousel:"+h+":change:loading",f),m["default"].on("a:carousel:"+h+":change:animating",f),m["default"].on("a:carousel:"+h+":change:fetchedItems",f),f(),e.attachRemoteOperation(function(a){var c=a.indexes;a=a.ids;return b.getCarouselItems(l.__assign(l.__assign({},k),{ids:a,indexes:c,offset:String(c[0]||0)}))}),[2]}})})}};q._operationNames=["getCarouselItems"];q.card=function(){return l.__awaiter(void 0,void 0,void 0,function(){return l.__generator(this,function(a){switch(a.label){case 0:return[4,
T.initCarousel()];case 1:return a.sent(),[2]}})})}});
