'use strict';mix_d("P13NSCCards__p13n-desktop-carousel:p13n-desktop-carousel__FlDR7eIw","exports tslib @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/A @p/a-carousel-framework @c/aui-modal @c/aui-untrusted-ajax @c/browser-operations @c/logger @c/aui-utils".split(" "),function(r,m,x,y,z,A,B,C,D,E,F,G,U){function f(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var H=f(x),I=f(z),g=f(A),k=f(B),J=f(C),K=f(D),L=f(E),t=f(F),n=f(G),N=function(a){return m.__awaiter(void 0,void 0,
void 0,function(){var c,b,d,e,l;return m.__generator(this,function(h){c=g["default"].cardRoot.querySelector(".report-problem-modal-root");if(!c)return[2];b={a11yOpenMessage:"A modal for internal users to report problems with recommendations",hideHeader:!1};d=K["default"].create("report-flag-modal",".report-problem-modal-root",b);e=t["default"].setup();l=g["default"].cardRoot.querySelector(".report-flag");e.define("show","click",function(){d.show()});e.attach("show",l);M(a,d);return[2]})})},M=function(a,
c){var b=g["default"].cardRoot.querySelector(".report-flag"),d=t["default"].setup();d.define("showFlag","mouseover",function(){b.classList.remove("report-flag-hide")});d.define("hideFlag","mouseout",function(){b.classList.add("report-flag-hide")});d.attach("showFlag",a);d.attach("hideFlag",a);var e=g["default"].cardRoot.querySelector(".internal-flag-form");e.onsubmit=function(c){return O(e,c,a)};k["default"].on("a:dropdown:selected:internal-flag-dropdown-name",function(a){e.querySelector(".internal-flag-env-data").setAttribute("data-problem-value",
a.value)});k["default"].on("a:popover:hide:"+c.id,function(){e.reset();var a=e.querySelector(".internal-flag-textarea").nextSibling;a&&a.classList.contains("report-problem-message")&&(a.innerText="")})},O=function(a,c,b){c.preventDefault();c=a.querySelector(".internal-flag-env-data").dataset;var d=a.querySelector(".internal-flag-dropdown").innerText,e=a.querySelector(".internal-flag-textarea"),l=e.firstElementChild.value;if(void 0===a.querySelector(".internal-flag-env-data").dataset.problemValue)return p(e,
!1,"Please select a problem."),!1;a=g["default"].cardRoot.querySelectorAll(".a-carousel-card");var h=P(b,a.length);b="Internal user reported issue with your widget: "+g["default"].cardRoot.querySelector(".a-carousel-heading").innerText;d=Q(a,h,d,l,c);L["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:"1b027359-e4c6-4e3c-92a8-0ff8a2ecb593",description:d,descriptionContentType:"text/amz-markdown-sim",
tags:[{id:"internal-problem-generated"},{id:c.problemValue}],title:b}}).then(function(a){p(e,!0,a)}).catch(function(a){p(e,!1,a)});return!1},P=function(a,c){if(!a.dataset.aCarouselOptions)return n["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=g["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(a){return JSON.parse(a).id}).slice(b,b+c)},
Q=function(a,c,b,d,e){for(var l="",h=0;h<a.length;h++){var u=a[h].querySelector(".a-dynamic-image");l+=(u?"![]("+u.src+")":"IMAGE MISSING")+"\nASIN: "+(c[h]?c[h]:"ASIN MISSING")+"\n\n"}return"**This SIM issue is created by the 'Report a Problem' internal tool. To know more, here's its wiki:https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Problem:** "+(b+"\n**CTI:** "+e.cti+" \n**CustomerID:** "+e.customerId+"\n**Device Type:** "+
e.deviceType+"\n**Facets:** ")+(e.facets+"\n**MarketplaceID:** "+e.marketplaceId+"\n**Content Reftag:** "+e.reftTag+"\n**SessionID:** ")+(e.sessionId+"\n**Strategy ID:** "+e.strategyId+(""!==d?"\n**Comment:** "+d:"")+"\n**List of ASINs:**\n\n"+l)},p=function(a,c,b){var d=a.nextSibling;d&&d.classList.contains("report-problem-message")||(d=document.createElement("h5"),d.classList.add("report-problem-message"),a.after(d));c?(d.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?
b.responseBody.response&&b.responseBody.response.id?d.innerHTML="Success, here's the <a href=\"https://issues.amazon.com/issues/"+b.responseBody.response.id+'" target="_blank">SIM issue</a> you created.':(n["default"].log("Fail to find the id of the SIM issue created in the response body of response data.","ERROR"),d.innerText="Success, but we could not find the link to the SIM."):(n["default"].log("The response body of response data is not an object.","ERROR"),d.innerText="Success, but we could not find the link to the SIM.")):
(d.classList.add("a-color-error"),d.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},v=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,w=/[^\/\-\[\]():\s]/,R=function(a){var c=k["default"].$("<div>")[0];c.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||"2",10),d=function(){var c=a.innerHTML;a.innerHTML=
"&hellip;";var b=a.clientHeight;a.innerHTML=c;return b}();if(b){if(d){var e=function(a){c.innerHTML=a;return Math.round(c.clientHeight/d)<=b},l=function(b,d){b=b.split(d);var e=Math.floor(a.clientWidth/12),h=function(b){c.classList.add("p13n-sc-offscreen-truncate");c.style.overflow="hidden";c.textContent=b;a.appendChild(c);b=a.clientWidth>=a.scrollWidth;a.removeChild(c);return b},l=function(a){var c=a.length-e;a.trim().length>e&&!h(a)&&Array.prototype.slice.call(a).map(function(a,b){return b>e&&b<=
c&&w.test(a)?"&shy;"+a:a});return a};return b.map(function(a){return l(a)}).join("")};return{truncate:function(){var b=a.innerHTML.trim(),d=a.textContent||"";b=l(b,v);a.appendChild(c);if(e(b))a.removeChild(c),a.innerHTML=b;else{var g=b.split(v);for(var f=1,m=g.length,k,p,q=0;f!==m;)if(k=Math.floor((m+f)/2),p=g.slice(0,k).join("")+"&hellip;",e(p)){if(1>=m-k){for(q=k;0<q&&!w.test(g[q-1]);)q--;break}f=k}else m=k;g=0===q?void 0:g.slice(0,q).join("")+"&hellip;";g?(a.innerHTML=g,a.setAttribute("title",
d)):(n["default"].log("Unable to successfully truncate line "+b,"ERROR"),a.removeChild(c))}}}}n["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else n["default"].log("Truncation element missing necessary line number data","ERROR")},S=function(a){a=a.getElementsByClassName("p13n-sc-truncate");Array.prototype.slice.call(a).map(function(a){var b=R(a);b&&(b.truncate(),a.classList.add("p13n-sc-truncated"),a.classList.remove("p13n-sc-truncate"),a.className=a.className.replace(/p13n-sc-line-clamp-\d/g,
""))})},T={initCarousel:function(a){return m.__awaiter(void 0,void 0,void 0,function(){var c,b,d,e,l,h,f;return m.__generator(this,function(n){switch(n.label){case 0:c=g["default"].cardRoot.classList.contains("p13n-sc-shoveler")?g["default"].cardRoot:g["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler")[0];b=I["default"].setup(["getCarouselItems"]);if(!c)return[2];d=J["default"].getCarousel(y.unscope(c));e=H["default"].getCarousel(c);l=c.dataset||{};h=d.getAttr("name");f=function(){k["default"].loadDynamicImage("[data-name]='"+
h+"' .p13n-sc-dynamic-image");S(c);null===a||void 0===a?void 0:a(c)};return[4,e.initialized];case 1:return n.sent(),N(c),k["default"].on("a:carousel:"+h+":change:pageSize",f),k["default"].on("a:carousel:"+h+":change:loading",f),k["default"].on("a:carousel:"+h+":change:animating",f),k["default"].on("a:carousel:"+h+":change:fetchedItems",f),f(),e.attachRemoteOperation(function(a){var c=a.indexes;a=a.ids;return b.getCarouselItems(m.__assign(m.__assign({},l),{ids:a,indexes:c,offset:String(c[0]||0)}))}),
[2]}})})}};r._operationNames=["getCarouselItems"];r.card=function(){return m.__awaiter(void 0,void 0,void 0,function(){return m.__generator(this,function(a){switch(a.label){case 0:return[4,T.initCarousel()];case 1:return a.sent(),[2]}})})}});
