(function(l){var f=window.AmazonUIPageJS||window.P,n=f._namespace||f.attributeErrors,b=n?n("EbooksBottomSheetAssets",""):f;b.guardFatal?b.guardFatal(l)(b,window):b.execute(function(){l(b,window)})})(function(l,f,n){l.when("jQuery","A").register("BottomSheet-Surface-Helper",function(b,f){return{createDeclarativeHandlers:function(b){b&&"function"===typeof b&&(f.declarative("carousel_item_clicked","click",b),f.declarative("carousel_item_clicked","keypress",function(k){var e=k.$event;!e||32!==e.which&&
13!==e.which||b(k)}))},setSurfaceCarouselSettings:function(){},getTitleTargetFromDeclarative:function(b){if(b&&b.$event&&"function"===typeof b.$event.preventDefault)return b.$event.preventDefault(),b.$currentTarget},orientationChange:function(){}}});l.register("KU-ReturnAndBorrowSheet-CSM",function(){function b(b,e){f.ues&&"function"===typeof ues&&ues("id",e,b)}function p(b,e){f.uet&&"function"===typeof uet&&uet("bb",b,{wb:1},e)}function h(b){f.uex&&"function"===typeof uex&&uex("ld",b,{wb:1})}return{bindRequest:b,
widgetBegin:p,widgetEnd:h,ManualTimeCSM:function(k){var e,c,f;this.manualWidgetBegin=function(){c=new Date};this.setWidgetSuffix=function(b){f=b};this.addRequestId=function(b){e=b};this.manualWidgetEnd=function(){var l=f?k+f:k;p(l,c);b(e,l);h(l)}}}});l.when("jQuery","A","a-modal","KU-ReturnAndBorrowSheet-CSM").register("KU-ReturnAndBorrowSheet-Helper",function(b,l,h,k){function e(b,e,k){f.ueLogError&&"function"===f.ueLogError&&f.ueLogError(e,{logLevel:b,attribution:"ku_dpx_return_and_borrow",message:"[KU-DPX] "+
k})}return{Helper:function(){function c(a){function b(a,d){d=d||2;return(Array(d).join("0")+a).slice(-d)}0===a.indexOf("#")&&(a=a.slice(1));3===a.length&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);if(6!==a.length)throw Error("Invalid HEX color - "+a);var c=(255-parseInt(a.slice(0,2),16)).toString(16),d=(255-parseInt(a.slice(2,4),16)).toString(16);a=(255-parseInt(a.slice(4,6),16)).toString(16);return"#"+b(c)+b(d)+b(a)}function m(a){a={name:a,hideHeader:!0};h.create(b("#"+a.name+"Trigger"),a).show()}function r(a){a.headers=
a.headers?a.headers:{};var c=g.CSRF_TOKEN;c&&""!==c||(c=l.state("csrfData")||{},c=c.csrfToken!==n?c.csrfToken:"");""===c?(e("FATAL",null,"NO CSRF token found"),v.showReturnAndBorrowErrorDialog()):(a.headers["X-CSRFToken"]=c,b.ajax(a))}if(1>arguments.length)return e("FATAL",null,"ReturnAndBorrowSheetHelper init: widgetContext missing"),!1;var g=arguments[0],v=this;this.returnAndBorrow=function(a,b,c,d,h,l){if(!g)return e("FATAL",null,"Calling returnAndBorrow without initializing"),!1;b={type:"POST",
url:g.RETURN_AND_BORROW_ENDPOINT+h,headers:{isFromDP:!0},contentType:"application/json",data:JSON.stringify(b),dataType:"json",timeout:5E3,error:function(a){d(a)},success:function(b,d,e){d=e&&e.getResponseHeader?e.getResponseHeader("x-amz-rid"):"";k.bindRequest(d,g.WIDGET_NAME_BOTTOM_SHEET);l&&l.addRequestId(d);k.bindRequest(d,a);k.widgetEnd(a);(function(){if(b.allSucceeded)return!0;if(b.succeededResults&&b.succeededResults.length){var a=b.succeededResults.filter(function(a){return a.requestedBorrowAsin===
g.ASIN&&a.workflowResponse&&"KLU_BORROW_SUCCEEDED"===a.workflowResponse.resultCode});return a&&a.length}return!1})()?f.location=g.TYP_BASE_URL+"\x26asin\x3d"+g.ASIN+"\x26subtype\x3d"+g.BORROW_SUB_TYPE+"\x26borrowingProgram\x3d"+g.PROGRAM+"\x26redirectionChecked\x3d1":c(b)}};k.widgetBegin(a);r(b)};this.getLoans=function(a,c){if(!g)return e("FATAL",null,"Calling getLoans without initializing"),!1;var f=new k.ManualTimeCSM(g.WIDGET_NAME_GET_LOANS),d={type:"POST",url:g.GET_LOANS_ENDPOINT+g.BORROW_BUTTON_REF_TAG,
contentType:"application/json",data:JSON.stringify({programName:g.PROGRAM,programChannel:g.CHANNEL?g.CHANNEL:"ALL_YOU_CAN_READ",currentPageKey:g.CURRENT_PAGE_KEY}),dataType:"html",timeout:1E4,success:function(d,c,e){c=e&&e.getResponseHeader?e.getResponseHeader("x-amz-rid"):"";k.bindRequest(c,g.WIDGET_NAME_GET_LOANS);k.bindRequest(c,g.WIDGET_NAME_BOTTOM_SHEET_ELAPSED);k.widgetEnd(g.WIDGET_NAME_GET_LOANS);e=b(d).find(".carouselItem").length;f.setWidgetSuffix("ActiveLoans"+e);f.addRequestId(c);f.manualWidgetEnd();
a(d,e)},error:function(a){c(a)}};k.widgetBegin(g.WIDGET_NAME_GET_LOANS);f.manualWidgetBegin();r(d)};this.cloneObject=function(a){return JSON.parse(JSON.stringify(a))};this.composeAbsoluteURL=function(a){return f.location.href.replace(/(:\/*[^/]*).*$/,"$1")+("/"===a.charAt(0)?"":"/")+a};this.showReturnAndBorrowErrorDialog=function(){m(g.ERROR_MODAL_PRELOAD_NAME)};this.showReturnAndBorrowIOUInfoDialog=function(){m(g.IOU_MODAL_PRELOAD_NAME)};this.invertColor=function(a){return a.startsWith("rgb")?(a=
a.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/),"rgb("+(255-a[1])+","+(255-a[2])+","+(255-a[3])+")"):c(a)}},logError:e}});l.when("jQuery","A","a-carousel-framework","a-button","KU-ReturnAndBorrowSheet-Helper","KU-ReturnAndBorrowSheet-CSM","BottomSheet-Surface-Helper").register("KU-ReturnAndBorrowSheet",function(b,p,h,k,e,c,m){function r(){var a=b("#shelfSpinnerContainer"),c=b("#shelfSpinnerContainer #shelfSpinner"),e=this;this.toggle=function(b){a.toggleClass("shelfSpinnerContainerShow a-spacing-small",
b);a.toggleClass("shelfSpinnerContainerHide aok-hidden",!b);c.toggleClass("aok-hidden",!b)};this.show=function(){e.toggle(!0)};this.hide=function(){e.toggle(!1)}}function g(){var a={},b=this;this.get=function(){return Object.keys(a)};this.count=function(){return b.get().length};this.reset=function(){a={}};this.update=function(c,d){d?a[c]=!0:delete a[c];return b.count()}}function v(){function a(b){var a;a=m&&"function"===typeof m.getTitleTargetFromDeclarative?m.getTitleTargetFromDeclarative(b):b.$target;
b=b.data.loanId;var c=a.siblings(".carouselSelectedMarker"),d=!c.length;d?(a.after('\x3cdiv class\x3d"carouselSelectedMarker carouselItem"\x3e'),c=a.position(),a.siblings(".carouselSelectedMarker").css({top:c.top+"px",left:c.left+"px",height:a.height()+"px",width:a.width()+"px"})):c.remove();0<u.update(b,d)?q.enable():q.disable()}function f(a,g){A.empty();a?(A.append(a),d(),A.removeClass("aok-hidden"),h.createAll(),h.initializeAll(),a=h.getCarousel(b("#shelfContainer",t)),m&&"function"===typeof m.setSurfaceCarouselSettings?
m.setSurfaceCarouselSettings(a):a&&a.setAttr&&a.setAttr("first_item_flush_left",!0),c.widgetEnd(x),y.setWidgetSuffix("ActiveLoans"+g),y.manualWidgetEnd()):(e.logError("ERROR",null,"Get loans request succeeded, but got empty response."),z());w.hide()}function k(a){e.logError("ERROR",null,"Get loans request failed with error: "+a);n();w.hide()}function d(){var a=b(B),c=0,d=0;a.load(function(){c++;d=Math.max(d,b(this).outerHeight());c===a.length&&l(d)})}function l(a){b(B).each(function(){var c=a-b(this).outerHeight();
b(this).css("margin-top",c+"px")});var c=a+5;b("#shelfContainer",t).find("ol").css("height",c+"px")}if(6>arguments.length)return e.logError("FATAL",null,"Carousel init: not properly constructed ["+arguments.length+"]"),!1;var v=arguments[0],q=arguments[1],n=arguments[2],z=arguments[3],t=arguments[4],x=arguments[5],y=arguments[6],w=new r,u=new g,A=b(t+" #shelfCarouselContent"),B=t+" .shelfCarouselContainer img";m&&"function"===typeof m.createDeclarativeHandlers?m.createDeclarativeHandlers(a):p.declarative("carousel_item_clicked",
"click",a);this.update=function(){w.show();A.addClass("aok-hidden");q.disable();u.reset();"function"===typeof v&&v(f,k)};this.getSelectedLoanIds=function(){return u.get()}}return{ReturnAndBorrowSheetWidget:function(){function a(a){r.addClass("aok-hidden");z.addClass("aok-hidden");l.when("mash").execute(function(b){b.dispatchEvent({type:"appOverlays."+("On"===a?"Hide":"Show")})});"On"===a?(n.removeClass("aok-hidden"),q.css("height",b(document).height()),q.removeClass("aok-hidden")):(n.addClass("aok-hidden"),
q.addClass("aok-hidden"))}function g(a){var b="",c;if(a.failedResults&&a.failedResults.length){var e=a.failedResults.filter(function(a){return a.requestedBorrowAsin===d.ASIN});e&&e.length&&(c=e[0],b=e[0].workflowResponse.resultCode)}switch(b){case "KLU_ALREADY_BORROWED":case "ALREADY_PURCHASED":u.hide();m.showReturnAndBorrowIOUInfoDialog();break;case "KLU_CONCURRENT_LIMIT_REACHED":f.location=d.RnB_PAGE_URL+"\x26ASIN\x3d"+d.ASIN+"\x26continueAction\x3d"+d.CONTINUE_ACTION+"\x26program\x3d"+d.PROGRAM+
"\x26channel\x3d"+d.CHANNEL+"\x26ref_\x3d"+d.BORROW_BUTTON_REF_TAG;break;case "KLU_BOTTOM_SHEET":u.show();break;case "KLU_MFA_FIX_UP":f.location=d.MFA_FIXUP_URL+"?asin\x3d"+d.ASIN+"\x26subtype\x3d"+d.BORROW_SUB_TYPE+"\x26program\x3d"+d.PROGRAM+"\x26channel\x3d"+d.CHANNEL+"\x26action\x3d"+d.CONTINUE_ACTION+"\x26authPageSource\x3dborrowInterrupt";break;case "BORROW_DEFERRED":f.location=d.MFA_FIXUP_URL+"?asin\x3d"+d.ASIN+"\x26loanId\x3d"+(c&&c.requestedReturnLoanId?c.requestedReturnLoanId:"")+"\x26subtype\x3d"+
d.BORROW_SUB_TYPE+"\x26program\x3d"+d.PROGRAM+"\x26channel\x3d"+d.CHANNEL+"\x26action\x3d"+d.CONTINUE_ACTION+"\x26authPageSource\x3dborrowInterrupt\x26authPageSourceVariant\x3dborrowDeferred";break;case "KLU_ASIN_INELIGIBLE":f.location=d.INELIGIBLE_ASIN_URL;break;case "KLU_CUSTOMER_NOT_SUBSCRIBED":f.location=d.NOT_SUBSCRIBED_URL+"?passThroughAsin\x3d"+d.ASIN+"\x26ref\x3dku_br_aw_ns";break;case "KLU_CUSTOMER_SUBSCRIBED_WITH_PAYMENT_PROBLEM":f.location=d.getPaymentProblemURL(m,d);break;default:h(a)}}
function h(a){a="function"===typeof a.statusCode?a.statusCode():a;e.logError("ERROR",null,"Error occurred while calling returnAndBorrow: "+JSON.stringify(a));u.hide();m.showReturnAndBorrowErrorDialog()}if(1>arguments.length)return e.logError("FATAL",null,"ReturnAndBorrowSheetWidget init: widgetContext missing"),!1;var d=arguments[0],m=new e.Helper(d),n=b("#"+d.MAIN_CONTAINER_ID),q=b("#"+d.SCRIM_SHEET_ID),r=n.find("#shelfAlertBox"),z=n.find("#shelfNullResponseAlertBox"),t=k("#"+d.MAIN_CONTAINER_ID+
" #returnAndContinueButton"),x=new c.ManualTimeCSM(d.WIDGET_NAME_BOTTOM_SHEET);n.css("background-color",d.THEME_COLOR);q.css("background-color",m.invertColor(d.THEME_COLOR));var y=new v(m.getLoans,t,function(){r.removeClass("aok-hidden")},function(){z.removeClass("aok-hidden")},"#"+d.MAIN_CONTAINER_ID,d.WIDGET_NAME_BOTTOM_SHEET,x),w={asin:d.ASIN,program:d.PROGRAM,channel:d.CHANNEL,loanId:""},u=this;p.declarative("return_and_continue","click",function(){var a=y.getSelectedLoanIds();if(t.isEnabled()&&
0<a.length){var b=[],c=0;a.forEach(function(a){var d=m.cloneObject(w);d.loanId=a;0<c++&&(d.asin="");b.push(d)});m.returnAndBorrow(d.WIDGET_NAME_RETURN_AND_BORROW+a.length,b,g,h,d.RETURN_AND_BORROW_BUTTON_REF_TAG)}});this.show=function(){a("On");c.widgetBegin(d.WIDGET_NAME_BOTTOM_SHEET_ELAPSED);y.update()};this.hide=function(){a("Off");c.widgetEnd(d.WIDGET_NAME_BOTTOM_SHEET_ELAPSED)};this.borrow=function(){c.widgetBegin(d.WIDGET_NAME_BOTTOM_SHEET);x.manualWidgetBegin();m.returnAndBorrow(d.WIDGET_NAME_BORROW,
[w],g,h,d.BORROW_BUTTON_REF_TAG,x)}}}});l.when("jQuery").register("KU-ReturnAndBorrowSheet-PaymentProblemURL",function(b){return{getPaymentProblemURL:function(f,h){h.PAYMENT_PROBLEM_URL=h.PAYMENT_PROBLEM_URL?h.PAYMENT_PROBLEM_URL:"/gp/digital/fiona/clarification/prime-borrow-failed";h.COR=h.COR?h.COR:b("#buyOneClick").attr("cor.0");return h.PAYMENT_PROBLEM_URL+"?ASIN\x3d"+h.ASIN+"\x26cor\x3d"+h.COR+"\x26error\x3dklu_customer_subscribed_with_payment_problem"}}});l.when("jQuery","A").execute("KU-DP-BottomSheet-Bind",
function(b,p){var h=b("#ku-borrow-button-spinner"),k=b("#borrow-button"),e=!1;k.click(function(b){e=!0;l.now("KU-ReturnAndBorrowSheet").execute("KU-DP-BottomSheet-Bind",function(b){b===n&&(k.hide(),h.removeClass("aok-hidden"),f.ue&&ue.count("ku_bottom_sheet_spinner_displayed",1))})});l.when("KU-DP-BottomSheet-Context","KU-ReturnAndBorrowSheet-PaymentProblemURL","KU-ReturnAndBorrowSheet","BottomSheet-Surface-Helper").execute("KU-DP-BottomSheet-Bind",function(c,f,l,g){h.hasClass("aok-hidden")||(h.addClass("aok-hidden"),
k.show());if(c.widgetContext){k.unbind("click");c=c.widgetContext;c.CHANNEL=c.CHANNEL?c.CHANNEL:"ALL_YOU_CAN_READ";c.RnB_PAGE_URL=c.RnB_PAGE_URL?c.RnB_PAGE_URL:"/kindle-dbs/hz/return?_encoding\x3dUTF8";c.CONTINUE_ACTION=c.CONTINUE_ACTION?c.CONTINUE_ACTION:"borrow";c.WIDGET_NAME_BOTTOM_SHEET_ELAPSED=c.WIDGET_NAME_BOTTOM_SHEET_ELAPSED?c.WIDGET_NAME_BOTTOM_SHEET_ELAPSED:"kuDpBottomSheetElapsed";c.MFA_FIXUP_URL=c.MFA_FIXUP_URL?c.MFA_FIXUP_URL:"/kindle-dbs/ku/auth-fixup";c.INELIGIBLE_ASIN_URL=c.INELIGIBLE_ASIN_URL?
c.INELIGIBLE_ASIN_URL:"/dp/"+c.ASIN;c.NOT_SUBSCRIBED_URL=c.NOT_SUBSCRIBED_URL?c.NOT_SUBSCRIBED_URL:"/kindle-dbs/ku2";c.THEME_COLOR=c.THEME_COLOR?c.THEME_COLOR:b("body").css("background-color");c.getPaymentProblemURL=f.getPaymentProblemURL;var n=new l.ReturnAndBorrowSheetWidget(c);k.click(function(a){n.borrow();a.preventDefault();return!1});p.declarative&&"function"===typeof p.declarative&&p.declarative("collapseBottomSheet","click",function(){n.hide()});g&&"function"===typeof g.orientationChange?
g.orientationChange(n.hide):p.on.orientationchange(function(){n.hide()});e&&n.borrow()}else k.attr("type","submit")})})});