(function(m){var d=window.AmazonUIPageJS||window.P,D=d._namespace||d.attributeErrors,y=D?D("MSXBooksDetailPageAsset",""):d;y.guardFatal?y.guardFatal(m)(y,window):y.execute(function(){m(y,window)})})(function(m,d,D){m.when("A","jQuery","MinimalLITBImageBlockATF").execute(function(y,f,c){function V(b){if("undefined"!==typeof b){var a=d.ue;if(a&&a.count){var c=a.count(b)||0;a.count(b,c+1)}}}function g(){var b=document.getElementById("litb-read-frame");if(b){if(J){b.contentWindow.postMessage(JSON.stringify({command:"readyLITB"}),
"*");return}b.contentWindow.postMessage(JSON.stringify({command:"readyLITB"}),"*");if(P>n)return;P++}setTimeout(g,v)}function p(b){z++;J?w(b):z>n?V("litbReadyMaxAttempts"):setTimeout(function(){p(b)},v)}function w(b){var a=document.getElementById("litb-read-frame");c.litbData&&c.litbData.showNewDesktopLitb&&a?(b=JSON.stringify({command:"initializeLITB",time:Date.now(),search:d.location.search,newSession:b}),a.contentWindow.postMessage(b,"*"),m(),a.focus()):"undefined"!=typeof SitbReader&&SitbReader.LightboxActions.openReader(c.litbData.litbReftag)}
function x(){var b=document.getElementById("litb-read-frame");c.litbData&&c.litbData.showNewDesktopLitb&&b&&(E||!K()&&!M||(m(),b.contentWindow.postMessage(JSON.stringify({command:"updateLITB",search:d.location.search}),b.src)),E=!1);M||C()}function m(){var b=document.getElementById("litb-read-frame");if(b){h=d.scrollY;var a=document.body;a.style.position="fixed";a.style.top="-"+h+"px";a.style.right="0";a.style.left="0";b.style.cssText="position:fixed; width:100%; height:100%; top:0px; left:0px; z-index:1000; display: block; border: 0 none;";
M=!0}}function Q(b){var a=document.getElementById("litb-read-frame");a&&(a.style.cssText="display: none",a=document.body,a.style.position="",a.style.top="",a.style.right="",a.style.left="",d.scrollTo(0,parseInt(h||"0",10)),M=!1,b&&C())}function C(){K()&&d.history.replaceState({},document.title,R(S()))}function W(b){var a;if(a="string"===typeof b.data)try{JSON.parse(b.data),a=!0}catch(c){a=!1}a&&(b=JSON.parse(b.data),a=b.command,"closeLITB"===a?b.depth?(E=!0,d.history.go(-1*b.depth),Q(!1)):Q(!0):"updateLITB"===
a&&b.search?(a=N(d.location.search),d.history.pushState({},document.title,R(H(b.search))),a.asin!==b.search.asin&&d.dispatchEvent(new PopStateEvent("popstate"))):"readyLITB"===a?J=!0:"reloadLITB"===a&&d.location.reload())}function N(b){var a={};0<b.length&&b.substr(1).split("\x26").forEach(function(b){b=b.split("\x3d");2===b.length&&(a[b[0]]=b[1])});return a}function A(b){var a="";Object.keys(b).forEach(function(c){0<a.length&&(a+="\x26");a+=c+"\x3d"+b[c]});return a}function H(b){var a="";d.location.search?
(a=N(d.location.search),a.asin=b.asin,a.revisionId=b.revisionId,a.format=b.format,a.depth=b.depth,a=A(a)):a=A(b);return"?"+a}function S(){var b="";d.location.search&&(b=N(d.location.search),delete b.asin,delete b.revisionId,delete b.format,delete b.depth,b=A(b));return"?"+b}function R(b){return d.location.origin+d.location.pathname+b+d.location.hash}function K(){var b=N(d.location.search);return b.asin&&b.format}var E=!1,J=!1,M=!1,F=f("#minimalImageBlock");(function(){d.ue&&d.ue.count&&ue.count("litbReadyMaxAttempts",
0);d.ue&&d.ue.count&&ue.count("litbReaderIframeSrcNotAvailable",0);if(c&&c.litbData&&(c.litbData.hasLitb&&c.litbData.litbReftag||c.litbData.showNewDesktopLitb)){F.click(p.bind(this,!0));var b=document.getElementById("litb-read-frame");b&&b.dataset&&b.dataset.src?b.src=b.dataset.src:V("litbReaderIframeSrcNotAvailable");c.litbData.showNewDesktopLitb&&b?(d.addEventListener("popstate",x,!1),d.addEventListener("message",W,!1),g(),b=N(d.location.search),b.asin&&b.format&&p(!1)):F.click(w.bind(this,!0))}})();
var v=100,n=50,P=0,z=0,h=0});m.when("A","jQuery","ImageBlockATF","AudibleAudioPlayer","cf").execute(function(y,f,c,V){function g(e){d.ue&&d.ue.count&&ue.count(e,0)}function p(e){if("undefined"!==typeof e){var a=d.ue;if(a&&a.count){var b=a.count(e)||0;a.count(e,b+1)}}}function w(){var e=d.innerWidth||document.body.offsetWidth;if(!(0>=e))if(e>c.windowWidthThreshold&&I.width()<=c.configWidths[0]){var e=c.configWidths[1],a=e/c.holderRatio,b=c.frontImageWidth,f=c.frontImageHeight;x(e,a,b,f)}else e<c.windowWidthThreshold&&
I.width()>c.configWidths[0]&&(e=c.configWidths[0],a=e/c.holderRatio,c.frontImageAspectRatio>c.holderRatio?(b=e,f=b/c.frontImageAspectRatio):(f=a,b=f*c.frontImageAspectRatio),x(e,a,b,f))}function x(e,a,b,d){if(0<e&&0<a&&0<b&&0<d){va.css("margin-left",e+c.centerColMargin).removeClass("centerColumn");wa.css("width",e);var y=a+c.containerMargin+c.flipLinkMinHeight;I.css("width",e).css("height",y);ua(b,d);ba.css("height",a-(a-q.outerHeight())/2);e=(ba.outerWidth()-q.outerWidth())/2;a=ba.outerHeight()-
q.outerHeight();l.css("top",a).css("left",e);ca.css("top",a+ma).css("left",e+b-ca.width());f(this).trigger("imageResize");O&&O.hide()}}function ua(e,a){q.css("width",e).css("height",a);var b=q.width(),c=q.height();l.css("width",b).css("height",c);"undefined"!==typeof t&&0<t.length&&(t.css("width",b).css("height",c),r.css("height",c),D&&ia&&(c=r.width(),B=(b-c)/2-2,r.removeClass("ieTransition").css("left",(b-c)/2),"front"==G?r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+B+"px)"):
r.css("transform","perspective(3000px) rotateY(90deg) translateZ("+B+"px)"),y.delay(function(){r.addClass("ieTransition")},10)))}function Q(){var e=L.find(".audioSamplePopover");m.when("jQuery","a-popover","ready").execute(function(a,b){O=b.create(xa,{activate:"onclick",position:"triggerRight",inlineContent:e})});X.click(C)}function C(){O&&O.show()}function W(e){e.bind("audioEnded",function(){Y.hide();Z.hide();X.show();da=0;O&&O.hide()});e.bind("audioPlaying",function(){Y.hide();X.hide();Z.show();
da=1;C()});e.bind("audioPaused",function(){Z.hide();X.hide();Y.show();da=0;O&&O.hide()})}function N(){da?T.pause():T.play()}function A(){var e=document.getElementById("litb-read-frame");if(e){if(ja){e.contentWindow.postMessage(JSON.stringify({command:"readyLITB"}),"*");return}e.contentWindow.postMessage(JSON.stringify({command:"readyLITB"}),"*");if(na>oa)return;na++}setTimeout(A,pa)}function H(e){qa++;ja?S(e):qa>oa?p("litbReadyMaxAttempts"):setTimeout(function(){H(e)},pa)}function S(e){var a=document.getElementById("litb-read-frame");
c.litbData&&c.litbData.showNewDesktopLitb&&a?(e=JSON.stringify({command:"initializeLITB",time:Date.now(),search:d.location.search,newSession:e}),a.contentWindow.postMessage(e,"*"),K(),a.focus()):"undefined"!=typeof SitbReader&&("back"==G&&SitbReader.currentBook&&SitbReader.currentBook.bookmarks?(a=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Cover").first,e=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Flap").first,a?SitbReader.LightboxActions.openReaderToPage(a):
e?SitbReader.LightboxActions.openReaderToPage(e):SitbReader.LightboxActions.openReader(c.litbData.litbReftag)):SitbReader.LightboxActions.openReader(c.litbData.litbReftag))}function R(){var a=document.getElementById("litb-read-frame");c.litbData&&c.litbData.showNewDesktopLitb&&a&&(u||!h()&&!ea||(K(),a.contentWindow.postMessage(JSON.stringify({command:"updateLITB",search:d.location.search}),a.src)),u=!1);ea||J()}function K(){var a=document.getElementById("litb-read-frame");if(a){ka=d.scrollY;var b=
document.body;b.style.position="fixed";b.style.top="-"+ka+"px";b.style.right="0";b.style.left="0";a.style.cssText="position:fixed; width:100%; height:100%; top:0px; left:0px; z-index:1000; display: block; border: 0 none;";ea=!0}}function E(a){var b=document.getElementById("litb-read-frame");b&&(b.style.cssText="display: none",b=document.body,b.style.position="",b.style.top="",b.style.right="",b.style.left="",d.scrollTo(0,parseInt(ka||"0",10)),ea=!1,a&&J())}function J(){h()&&d.history.replaceState({},
document.title,z(P()))}function M(a){var b;if(b="string"===typeof a.data)try{JSON.parse(a.data),b=!0}catch(c){b=!1}b&&(a=JSON.parse(a.data),b=a.command,"closeLITB"===b?a.depth?(u=!0,d.history.go(-1*a.depth),E(!1)):E(!0):"updateLITB"===b&&a.search?(b=F(d.location.search),d.history.pushState({},document.title,z(n(a.search))),b.asin!==a.search.asin&&d.dispatchEvent(new PopStateEvent("popstate"))):"readyLITB"===b?ja=!0:"reloadLITB"===b&&d.location.reload())}function F(a){var b={};0<a.length&&a.substr(1).split("\x26").forEach(function(a){a=
a.split("\x3d");2===a.length&&(b[a[0]]=a[1])});return b}function v(a){var b="";Object.keys(a).forEach(function(c){0<b.length&&(b+="\x26");b+=c+"\x3d"+a[c]});return b}function n(a){var b="";d.location.search?(b=F(d.location.search),b.asin=a.asin,b.revisionId=a.revisionId,b.format=a.format,b.depth=a.depth,b=v(b)):b=v(a);return"?"+b}function P(){var a="";d.location.search&&(a=F(d.location.search),delete a.asin,delete a.revisionId,delete a.format,delete a.depth,a=v(a));return"?"+a}function z(a){return d.location.origin+
d.location.pathname+a+d.location.hash}function h(){var a=F(d.location.search);return a.asin&&a.format}function b(a){ia?"click"==a.type?"front"==G?(G="back",q.removeClass("frontUnrotated frontUnrotatedHover").addClass("frontRotated"),t.removeClass("backUnrotated backUnrotatedHover").addClass("backRotated"),r.css("transform","perspective(3000px) rotateY(90deg) translateZ("+B+"px)"),fa.addClass("a-hidden"),ga.removeClass("a-hidden"),ha.addClass("flipToBackImgRotate"),p("booksImageFlipToBackCount")):
(G="front",q.removeClass("frontRotated frontRotatedHover").addClass("frontUnrotated"),t.removeClass("backRotated backRotatedHover").addClass("backUnrotated"),r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+B+"px)"),ga.addClass("a-hidden"),fa.removeClass("a-hidden"),ha.removeClass("flipToBackImgRotate"),p("booksImageFlipToFrontCount")):"mouseenter"==a.type?"front"==G?(q.removeClass("frontUnrotated").addClass("frontUnrotatedHover"),t.removeClass("backUnrotated").addClass("backUnrotatedHover"),
r.css("transform","perspective(3000px) rotateY(-55deg) translateZ("+B+"px)")):(q.removeClass("frontRotated").addClass("frontRotatedHover"),t.removeClass("backRotated").addClass("backRotatedHover"),r.css("transform","perspective(3000px) rotateY(80deg) translateZ("+B+"px)")):"front"==G?(q.removeClass("frontUnrotatedHover").addClass("frontUnrotated"),t.removeClass("backUnrotatedHover").addClass("backUnrotated"),r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+B+"px)")):(q.removeClass("frontRotatedHover").addClass("frontRotated"),
t.removeClass("backRotatedHover").addClass("backRotated"),r.css("transform","perspective(3000px) rotateY(90deg) translateZ("+B+"px)")):"click"==a.type?"front"==G?(l.removeClass("bookCanvasTransformHover").addClass("rotated"),fa.addClass("a-hidden"),ga.removeClass("a-hidden"),ha.addClass("flipToBackImgRotate"),G="back",p("booksImageFlipToBackCount")):(l.removeClass("rotated rotatedHover"),ga.addClass("a-hidden"),fa.removeClass("a-hidden"),ha.removeClass("flipToBackImgRotate"),G="front",p("booksImageFlipToFrontCount")):
"mouseenter"==a.type?"front"==G?l.addClass("bookCanvasTransformHover"):l.removeClass("rotated").addClass("rotatedHover"):"front"==G?l.removeClass("bookCanvasTransformHover"):l.removeClass("rotatedHover").addClass("rotated")}function a(){aa.addClass("parentImage");r.addClass("bookSpine").removeClass("a-hidden");l.addClass("bookCanvasTransition");q.addClass("bookFrontTransition");y.delay(function(){l.addClass("bookCanvasTransformHover");y.delay(function(){l.removeClass("bookCanvasTransformHover")},
1500)},50)}function ta(){var a=r.outerWidth(),b=q.outerWidth();B=(b-a)/2-2;r.css("left",(b-a)/2).css("transform","perspective(3000px) rotateY(-90deg) translateZ("+B+"px)");q.addClass("ieTransition ieBookShadow").css("transform-origin","50% 50% -"+a/2+"px");t.addClass("ieTransition backLanding ieBookShadow").removeClass("a-hidden").css("transform-origin","50% 50% -"+a/2+"px");r.addClass("ieTransition ieBookShadow").removeClass("a-hidden").css("transform-origin","50% 50% -"+a/2+"px");y.delay(function(){t.removeClass("backLanding").addClass("backUnrotated");
q.addClass("frontUnrotated");r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+B+"px)")},50);q.mouseenter(function(){r.css("transform","perspective(3000px) rotateY(-75deg) translateZ("+B+"px)")});q.mouseleave(function(){r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+B+"px)")});U.removeClass("a-hidden")}var u=!1,ja=!1,ea=!1,I=f("#imageBlock"),aa=I.find("#img-wrapper"),ba=I.find("#imageBlockContainer"),l=I.find("#img-canvas"),t=l.find(".backImage"),r=l.find(".sideImage"),
q=l.find(".frontImage"),ca=f("#imageBlockOuter").find("#sitbLogo"),U=I.find(".flipImageToBack"),L=I.find(".sampleBookAudio"),ra=0,G="front",D=0,da=0,X=L.find(".audioListenText"),Z=L.find(".audioPlayingText"),Y=L.find(".audioPausedText"),sa=L.find(".audioText"),xa=L.find(".audioPopoverTrigger"),T,fa=U.find(".flipToBackText"),ga=U.find(".flipToFrontText"),ha=U.find(".flipToBackImg"),ia=f.browser.msie||!!navigator.userAgent.match(/Trident/),O,wa=f("#leftCol"),va=f("#centerCol"),B=0,la=f("#imageBlockOuter").find("#sitbLogoImg"),
ma=parseInt(I.css("margin-top"));(function(){g("booksImageFlipToBackCount");g("booksImageFlipToFrontCount");g("litbReadyMaxAttempts");g("litbReaderIframeSrcNotAvailable");var e=aa.offset(),u=q.offset();if(u){var k=u.top-e.top,e=u.left-e.left,u=q.outerWidth(),n=q.outerHeight(),h=aa.outerHeight()-(aa.outerHeight()-q.outerHeight())/2,m=r.outerWidth();aa.css("position","relative");ca.css("top",k+ma).css("left",e+u-ca.width());l.css("position","absolute").css("top",k).css("left",e).css("width",u).css("height",
n);q.css("position","absolute").css("top","0").css("left","0");t.css("position","absolute").css("top","0").css("left","0");r.css("position","absolute").css("top","0").css("left","-"+m+"px");ba.css("height",h)}c.audibleData&&c.audibleData.audioSampleSrc&&(T=new V,k={},k.audioSrc=c.audibleData.audioSampleSrc,k.audioId="img-blk-audio-sample",k.audioControllerId=L,k.flashPlayerUrl=c.audibleData.flashPlayerUrl,k.bindEventsCallback=W,T.init(k));u=1;k=["Perspective","TransformStyle","TransformOrigin","BackfaceVisibility",
"Transition"];for(e=0;e<k.length;e++)if(u){for(var u=k[e],n=["Webkit","Moz","O","ms"],h=document.createElement("div"),m=!1,v=0;v<n.length;v++)n[v]+u in h.style&&(m=m||!0);"Perspective"===u&&"WebkitPerspective"in h.style&&(m=!1,h.id="test3d",document.body.appendChild(h),3===h.offsetHeight&&(m=!0),h.parentNode.removeChild(h));u=m}ra=u;k="undefined"!==typeof t&&0<t.length;(D=ra&&k)?(k=q.width(),e=q.height(),0<k&&0<e&&(l.addClass("image-3d"),t.css("width",k).css("height",e),r.css("height",e),ia?ta():
(a(),t.addClass("bookBack").removeClass("a-hidden"),U.removeClass("a-hidden")),y.declarative("flip-action",["click","mouseenter","mouseleave"],b)),T&&T.isPlayerAvailable?U.addClass("a-span6"):U.addClass("a-span12")):l.addClass("image-2d");c&&c.litbData&&(c.litbData.hasLitb&&c.litbData.litbReftag||c.litbData.showNewDesktopLitb)&&(la.removeClass("a-hidden"),la.click(H.bind(this,!0)),I.click(H.bind(this,!0)),(k=document.getElementById("litb-read-frame"))&&k.dataset&&k.dataset.src?k.src=k.dataset.src:
p("litbReaderIframeSrcNotAvailable"),c.litbData.showNewDesktopLitb&&k?(d.addEventListener("popstate",R,!1),d.addEventListener("message",M,!1),A(),k=F(d.location.search),k.asin&&k.format&&H(!1)):(la.click(S.bind(this,!0)),I.click(S.bind(this,!0))),k={hasComponents:!0,components:[{name:"mainimage"}]},"function"===typeof d.markFeatureInteractive&&d.markFeatureInteractive("booksImageBlock",k));T&&T.isPlayerAvailable&&(D?L.addClass("a-span6"):L.addClass("a-span12"),Z.hide(),Y.hide(),L.removeClass("a-hidden"),
sa.children().click(N),k=parseInt,e=X.outerWidth(),u=Z.outerWidth(),n=Y.outerWidth(),h=0,0<e&&0<u&&0<n&&(h=Math.max(e,u,n)+5),(k=k(h))&&0<k&&sa.css("width",k),Q());c.disableResize||f(d).resize(w)})();var pa=100,oa=50,na=0,qa=0,ka=0});m.when("a-modal-handlers").execute("mark-booksimageblock-interactive-time",function(){"function"===typeof d.markFeatureInteractive&&d.markFeatureInteractive("booksImageBlock",{hasComponents:!0,components:[{name:"thumbnail"}]})});m.when("A","jQuery","ImageBlockATF","ImageGalleryMarkup").execute(function(d,
f,c){function m(){var a=c.imageGalleryData;if(a&&0<a.length){n={};P=a.length;for(var b=0;b<a.length;b++)n["ig-thumb-"+b]=a[b]}}function g(){v=H.height();0<S.length&&(v-=S.height());if(f.browser.msie&&7==f.browser.version){var a=R.outerHeight()-R.height();a&&0<a&&(v-=a)}if(v&&0<v){R.css("height",v);var a=M.height(),b=M.width();K.css("height",a).css("width",b).data("height",a).data("width",b)}}function p(){if(0<H.length){g();x();if(0<P)for(var a=0;a<P;a++){var b="ig-thumb-"+a,b=f('\x3cdiv class\x3d"ig-thumb-image"\x3e\x3cimg class\x3d"ig-thumb-inner '+
(b==h?"selected":"")+'" id\x3d"'+b+'" src\x3d"'+n[b].thumbUrl+'"\x3e\x3c/div\x3e');J.append(b)}zoomOptions=Q();z.setImageData(zoomOptions);z.attachZoomEvents()}}function w(){var a=n[h].dimensions[0],b=n[h].dimensions[1];E.css("max-width",a).css("max-height",b).removeClass("image-stretch-horizontal image-stretch-vertical");E.addClass(D(a,b))}function x(){n[h]&&(w(),E.attr("src",n[h].mainUrl))}function D(a,b){var c=K.data("width")/K.data("height"),d="image-stretch-vertical";a/b>c&&(d="image-stretch-horizontal");
return d}function Q(){var a={};n[h]&&(a.containerId="igInner",a.imageId="igImage",a.imageWidth=n[h].dimensions[0],a.imageHeight=n[h].dimensions[1]);return a}function C(){n&&J.find(".ig-thumb-inner").click(function(){var a=this.id,c=f(this),d=n[a];!c.hasClass("selected")&&d&&(h=a,J.find(".selected").removeClass("selected"),c.addClass("selected"),z.detachEvents(),E.addClass("a-hidden"),F.show(),document.getElementById("igImage").onload=b,x(),a=Q(),z.setImageData(a))})}function W(){var a=d.viewport();
A.closest(".a-popover-modal").css("width",.75*a.width).css("height",.75*a.height);g();z.detachEvents();w();a=Q();z.setImageData(a);z.attachZoomEvents()}function N(){d.capabilities.orientation&&(d.on("orientationchange",function(){W()}),d.on("a:popover:afterHide:imageGallery",function(){d.off("a:popover:afterHide:imageGallery");d.on("a:popover:beforeShow:imageGallery",function(){W()})}))}var A=f("#imgGalleryContent"),H=A.closest(".a-popover-wrapper"),S=H.find(".a-popover-header"),R=H.find(".a-popover-inner"),
K=A.find("#igInner"),E=K.find("#igImage"),J=A.find(".ig-thumbs"),M=A.find(".ig-main-image"),F=A.find(".loading-bar"),v=0,n=null,P=0,z=new function(){function a(){l.bind("touchstart.ig touchmove.ig",function(d){b(d);l.unbind("touchstart.ig touchmove.ig");l.bind("touchmove.ig",function(a){b(a)});l.bind("touchend.ig",function(b){c.zoomOut();l.unbind("touchstart.ig touchmove.ig touchend.ig");a()})})}function b(a){q&&a.preventDefault();var d,f={},h=g.width(),l=g.height();d=a.pageX-g.offset().left;a=a.pageY-
g.offset().top;f.x=t?d*n/h-d:0;f.y=r?a*p/l-a:0;c.zoomIn(f)}var c={},h=null,m=null,n=0,p=0,g=null,l=null,t=!1,r=!1,q=d.capabilities.touch;c.setImageData=function(a){h=a.containerId;m=a.imageId;n=a.imageWidth;p=a.imageHeight;g=f("#"+h);l=f("#"+m);t=0<n&&0<g.length&&n>g.width();r=0<p&&0<g.length&&p>g.height()};c.attachZoomEvents=function(){if(t||r)g.addClass("zoomable"),q?a():l.click(function(a){g.hasClass("zoomed-in")?(c.zoomOut(),l.unbind("mousemove")):g.hasClass("zoomed-out")&&(b(a),l.mousemove(function(a){b(a)}))})};
c.zoomIn=function(a){l.css("top",-1*a.y);l.css("left",-1*a.x);g.removeClass("zoomed-out").addClass("zoomed-in")};c.zoomOut=function(){g.removeClass("zoomed-in").addClass("zoomed-out");l.css("top","auto").css("left","auto")};c.detachEvents=function(){c.zoomOut();l.unbind();g.removeClass("zoomable")};return c},h;0<A.length&&(h="ig-thumb-0",F.hide(),m(),p(),C(),N());var b=function(){F.hide();E.removeClass("a-hidden");z.attachZoomEvents()}});m.when("A","jQuery").execute(function(d,f){if(f("#imageBlockThumbs").length){var c=
function(){var c=f("#imgThumbs"),g=c.data("a-modal"),p=d.viewport();g.width=.75*p.width;g.height=.75*p.height;c.data("a-modal",g)};"use strict";c();d.on("resize",c)}});"use strict";m.when("A","jQuery","msxUtility","ready","atf").execute(function(d,f,c){function V(p){var C=f("\x3cdiv\x3e\x3c/div\x3e").html(p);c.digestPageStates(C);C=null;m.when("responsiveMediaTabsLoadComplete").execute(function(){var c=f(p).find("#twister");c.addClass("no-swatches");x.eq(0).html(c);(c=w[0].getElementsByClassName("olpLink")[0])&&
"show-all-offers-display"===c.parentElement.getAttribute("data-action")?w.find(".olpLink").eq(0).parent().addClass("tabHidden"):w.find(".olpLink").eq(0).addClass("tabHidden");w.find(".mediaMatrix").eq(0).removeClass("tabHidden");d.trigger("mediaMatrixLazyLoadComplete")});C=f(".otherSellers.mediaMatrix");0<C.length&&C.eq(0).bind("click",g)}function g(d){c.postMetric("mmt-media-matrix-glance-view");f(d.currentTarget).unbind("click",g)}var p=d.state("media-matrix-variables");if(p){var p="/gp/mediatabs/mediamatrix?"+
f.param({asin:p.currentAsin,isMediaMatrixAjaxCall:1,productGroupId:p.productGroupID}),w=f("#mediaTabsHeadings"),x=f("#mediaTab_content_all").find("#MediaMatrix"),D=f("#mediaTab_content_all").find("#MediaMatrixSlot");x&&0<x.length&&D&&0<D.length&&f.ajax({method:"GET",url:p,dataType:"text",success:function(d){d&&/\S/.test(d)?V(d):c.postMetric("mmt-media-matrix-ajax-call-fail")},error:function(d){c.postMetric("mmt-media-matrix-ajax-call-fail")}})}});"use strict";m.when("A","jQuery").register("msxUtility",
function(m,f){return{digestPageStates:function(c){c.find("script[type\x3d'a-state']").each(function(c,d){var f,w,x=d.dataset;x&&x.aState&&(f=JSON.parse(x.aState).key,w=JSON.parse(d.innerText));f&&w&&m.state(f,w)})},postMetric:function(c){if("undefined"!==typeof c){var f=d.ue;if(f){var g=f.count(c)||0;f.count(c,g+1)}}}}})});
/* ******** */
(function(e){var f=window.AmazonUIPageJS||window.P,k=f._namespace||f.attributeErrors,d=k?k("OffersBooksDetailPageAsset",""):f;d.guardFatal?d.guardFatal(e)(d,window):d.execute(function(){e(d,window)})})(function(e,f,k){e.when("A","jQuery","atf").execute(function(d,c,e){var b=c("#rbbContainer");b.find(".rbbHeaderLink").attr("href","javascript:void(0);");b.find(".rbbHeader .displayNone i.prime").hide();b.find(".rbbHeader .displayNone .primeBadge").hide();b.find(".rbbHeader .ubbPrimeBadge").hide();b.find(".rbbHeader .prime-plus-price").hide();
b.find(".rbbHeader .displayNone").removeClass("displayNone");c("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();var f=c("#buyDealSection").length;c("#rbbContainer .rbbSection .rbbHeader").click(function(a){c(a.target);a=c(this);a=a.hasClass("rbbHeader")?a:a.parents(".rbbHeader");if(a.parents(".rbbSection").hasClass("selected"))return!1;b.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");b.find(".selected .offer-price").removeClass("a-color-price a-size-medium").addClass("a-color-base a-size-base");
b.find("i.a-icon.prime").hide();b.find(".primeBadge").hide();b.find(".ubbPrimeBadge").hide();var d=b.find(".prime-plus-price-grid");d.hasClass("hidden")?d.removeClass("hidden").show():d.addClass("hidden").hide();b.find(".prime-plus-price").show();a.parents(".rbbSection").removeClass("unselected").addClass("selected");a.parents(".rbbSection").toggleClass("dp-accordion-active",500);a.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");a.find(".offer-price").removeClass("a-color-base a-size-base").addClass("a-color-price a-size-medium");
a.find("#priceBadgeValue").removeClass("a-size-medium").addClass("a-size-base");a.find("i.a-icon.prime").show();a.find(".primeBadge").show();a.find(".prime-plus-price").hide();c("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-base").addClass("a-color-price");a.find(".ubbPrimeBadge").show();var e=c(this).attr("id"),g,h;b.find(".rbbSection").each(function(b,a){c(a).find(".rbbHeader")[0].id===e?g=c(a):c(a).hasClass("selected")&&(h=c(a))});h.find(".rbbContent").slideUp(500,
function(){h.removeClass("selected").addClass("unselected");h.toggleClass("dp-accordion-active",500)});g.find(".rbbContent").slideDown(500);c.browser.msie&&7===parseInt(c.browser.version,10)&&(g.find(".rbbContent").css("display","inline"),setTimeout(function(){g.find(".rbbContent").css("display","block")},505));if(f&&"undefined"!=typeof UDPDealView)if(c("#gbld_header_message").show(),"buyDealSection"===e)UDPDealView.prototype.onSelectLDBuybox();else UDPDealView.prototype.onSelectRegularBuybox();return!0})});
e.when("A","jQuery").execute(function(d,c){c("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var d=c("#addToCart"),b=d.attr("action").replace("ref\x3ddp_start-bbf_1_glance","ref\x3ddp_start-ubbf_1_glance");d.attr("action",b);return!0});e.when("a-popover").execute(function(e){var b=c("#usedItemConditionInfoLink"),f=e.create(b,{width:250,position:"triggerBottom",activate:d.capabilities.touch?"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",
name:"usedItemConditionDetailsPopover",dataStrategy:"preload"});b.mouseleave(function(){f.hide()})})})});
/* ******** */
(function(k){var l=window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors,e=m?m("PInfoBooksDetailPageAsset",""):l;e.guardFatal?e.guardFatal(k)(e,window):e.execute(function(){k(e,window)})})(function(k,l,m){k.when("A","jQuery","atf").execute(function(e,a,w){var h,d=0;k.when("DPClientLogger").execute(function(){"undefined"!=typeof l.DPClientLogger&&(h=new l.DPClientLogger.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))});a("#bookDetails_feature_div .hero-more").click(function(b){b.preventDefault();
b=a(this).attr("data-popupID");var g=a("#"+b),f=a(this).offset().left+a(this).width()/2,c=a("#popupContent").offset().left,f=(f-c)/a("#popupContent").width()*100;a("#"+b+" .pointer").css({left:f+"%"});a("#popupContent .details-popup").filter(":visible").length?a("#popupContent .details-popup").filter(":visible").attr("id")!==b?(a("#popupContent .details-popup").filter(":visible").slideToggle(300),g.slideToggle(300)):g.slideUp(300):(g.slideDown(300),a(this).hasClass("hero-more")&&a("html,body").animate({scrollTop:a("#bookDetails_feature_div").offset().top-
50},600));h&&!d&&(h.logImpression("ma-books-br-details"),d=1)});a("#bookDetails_feature_div .moreNarratorLink").click(function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")||location.hostname==this.hostname){var b=a(this.hash),b=b.length?b:a("[name\x3d"+this.hash.slice(1)+"]");b.length&&a("html,body").animate({scrollTop:b.offset().top},1E3);return!1}});a("#bookDetails_feature_div .details-popup button").click(function(b){a(this).parent().slideUp(300)})});k.when("A","jQuery",
"atf").execute(function(e,a,k){function h(){var d=parseInt(a("#byline").width()),b=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(b+=a(this).outerWidth())});b+=a("#byline .more").outerWidth();if(b>d){var g=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(c){b>d&&c<g-1&&(c=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),b-=c,a("#byline .moreCount").html(a("#byline .author").length-a("#byline .author.notFaded").length),
a("#byline .more").addClass("notFaded").fadeIn(10))})}else if(b<d&&a("#byline .author.notFaded").length<a("#byline .author").length){var f=d-b;a("#byline .author").each(function(){if(!a(this).hasClass("notFaded")){var c=a(this).outerWidth();c<=f?(f-=c,a(this).addClass("notFaded").fadeIn(10),c=a("#byline .author").length-a("#byline .author.notFaded").length,0===c?a("#byline .more").removeClass("notFaded").fadeOut(10):(a("#byline .moreCount").html(c),a("#byline .more").addClass("notFaded").fadeIn(10))):
f=0}})}}a("#byline .showMoreLink").click(function(){a("#byline .author").each(function(){a(this).hasClass("notFaded")||a(this).addClass("notFaded").fadeIn(0);a("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});a("#byline .contributorNameID").mouseenter(function(){var d=a(this).attr("data-asin"),b={},g="isAjaxComplete_"+d,f="isAjaxInProgress_"+d,c=e.state("popoverImage-state");b.entityID=d;"1"!==c[g]&&"1"!==c[f]&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",
data:b,dataType:"html",timeout:1E3,success:function(b){a("#contributorImageContainer"+d).get(0).innerHTML=b;c[g]="1";e.state("popoverImage-state",c)},error:function(){c[f]="0";e.state("popoverImage-state",c)}}),c[f]="1",e.state("popoverImage-state",c))});(function(d){var b=parseInt(d.width()),g=parseInt(d.find(".more").outerWidth()),f=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(f+=a(this).outerWidth())});a("#byline .more").attr("data-width",g);var c=b-g;if(c>f)d.find(".author").each(function(){var b=
a(this).index();3<=parseInt(b)?(b=a(this).outerWidth(),a(this).attr("data-width",b),b<c?(c-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(c=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),c-=b)});else{var e=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(b){c<f&&b<e-1&&(b=a(this).outerWidth(),f-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}b=d.find(".author").length-d.find(".author.notFaded").length;
0<b&&(d.find(".moreCount").html(b),d.find(".more").fadeIn("slow"),d.find(".more").addClass("notFaded"))})(e.$("#byline"));a(l).resize(function(){h()})});k.when("A","jQuery","atf").execute(function(e,a,k){function h(){var d=parseInt(a("#bylineInfo").width()),b=0;a("#bylineInfo .author").each(function(){a(this).is(".notFaded")&&(b+=a(this).outerWidth())});b+=a("#bylineInfo .more").outerWidth();if(b>d){var e=a("#bylineInfo .author.notFaded").length;a(a("#bylineInfo .author.notFaded").get().reverse()).each(function(c){b>
d&&c<e-1&&(c=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),b-=c,a("#bylineInfo .moreCount").html(a("#bylineInfo .author").length-a("#bylineInfo .author.notFaded").length),a("#bylineInfo .more").addClass("notFaded").fadeIn(10))})}else if(b<d&&a("#bylineInfo .author.notFaded").length<a("#bylineInfo .author").length){var f=d-b;a("#bylineInfo .author").each(function(){if(!a(this).hasClass("notFaded")){var b=a(this).outerWidth();b<=f?(f-=b,a(this).addClass("notFaded").fadeIn(10),
b=a("#bylineInfo .author").length-a("#bylineInfo .author.notFaded").length,0===b?a("#bylineInfo .more").removeClass("notFaded").fadeOut(10):(a("#bylineInfo .moreCount").html(b),a("#bylineInfo .more").addClass("notFaded").fadeIn(10))):f=0}})}}a("#bylineInfo .showMoreLink").click(function(){a("#bylineInfo .author").each(function(){a(this).hasClass("notFaded")||a(this).addClass("notFaded").fadeIn(0);a("#bylineInfo .more").removeClass("notFaded").fadeOut(0)});return!1});a("#bylineInfo .contributorNameID").mouseenter(function(){var d=
a(this).attr("data-asin"),b={},g="isAjaxComplete_"+d,f="isAjaxInProgress_"+d,c=e.state("popoverImage-state");b.entityID=d;"1"!==c[g]&&"1"!==c[f]&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:b,dataType:"html",timeout:1E3,success:function(b){a("#contributorImageContainer"+d).get(0).innerHTML=b;c[g]="1";e.state("popoverImage-state",c)},error:function(){c[f]="0";e.state("popoverImage-state",c)}}),c[f]="1",e.state("popoverImage-state",c))});(function(d){var b=
parseInt(d.width()),e=parseInt(d.find(".more").outerWidth()),f=0;a("#bylineInfo .author").each(function(){a(this).is(".notFaded")&&(f+=a(this).outerWidth())});a("#bylineInfo .more").attr("data-width",e);var c=b-e;if(c>f)d.find(".author").each(function(){var b=a(this).index();3<=parseInt(b)?(b=a(this).outerWidth(),a(this).attr("data-width",b),b<c?(c-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(c=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),c-=b)});else{var h=
a("#bylineInfo .author.notFaded").length;a(a("#bylineInfo .author.notFaded").get().reverse()).each(function(b){c<f&&b<h-1&&(b=a(this).outerWidth(),f-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}b=d.find(".author").length-d.find(".author.notFaded").length;0<b&&(d.find(".moreCount").html(b),d.find(".more").fadeIn("slow"),d.find(".more").addClass("notFaded"))})(e.$("#bylineInfo"));a(l).resize(function(){h()})});k.when("A","jQuery","DynamicIframe","ProductDescriptionData","cf").execute(function(e,
a,k,h){function d(){t=0;var a=Math.min(m,p.length);g(0,a)}function b(){0<n.length&&0<q.length&&(r="collapsed",n.removeClass("a-hidden"),n.click(function(){"collapsed"===r?(v?q.animate({height:"show"}):(q.removeClass("extraReviews"),g(t,p.length),v=1),n.removeClass("collapsed").addClass("expanded"),r="expanded"):(q.animate({height:"hide"}),n.removeClass("expanded").addClass("collapsed"),r="collapsed")}))}function g(b,c){var d;for(d=b;d<c;d++){var e={};e.iframeId="er_iframe_"+d;e.iframeWrapperId="er_iframe_wrapper_"+
d;e.iframeContainerId="er_container_"+d;e.iframeExpanderId="er_expander_"+d;e.iframeColumnId="er_column_"+d;var g=e,h=p[d],m="\x3ch3 class\x3d'erSource'\x3e"+h.source+"\x3c/h3\x3e\x3cdiv class\x3d'erContent'\x3e"+h.content+"\x3c/div\x3e";h.footnote&&(m=m+"\x3cem class\x3d'erFootnote'\x3e"+h.footnote+"\x3c/em\x3e");g.encodedIframeContent=m;e.initialResizeCallback=f;g=e;h={};h.id=a("#"+g.iframeId);h.column=a("#"+g.iframeColumnId);h.wrapper=a("#"+g.iframeWrapperId);h.container=a("#"+g.iframeContainerId);
h.expander=a("#"+g.iframeExpanderId);h.iframeObj=new k(g);h.state="full";g=h;u[e.iframeId]=g;g.column.removeClass("extraReviews");g&&"undefined"!=typeof g.iframeObj&&"function"==typeof g.iframeObj.createIframe&&g.iframeObj.createIframe();l(g);t++}}function f(a){(a=u[a])&&170<a.wrapper.outerHeight()&&(a.container.css("height",140),a.expander.removeClass("a-hidden expanded").addClass("collapsed"),a.state="partial")}function c(a){(a=u[a])&&"full"===a.state&&a.container.css("height",a.wrapper.outerHeight())}
function l(b){if(b&&"undefined"!=typeof b.iframeObj&&"function"==typeof b.iframeObj.resizeIframe)e.on("resize",function(){b.iframeObj.resizeIframe(c)});b&&b.expander&&b.expander.click(function(){"partial"===b.state?(b.container.animate({height:b.wrapper.outerHeight()}),b.expander.removeClass("collapsed").addClass("expanded"),b.state="full"):(b.container.animate({height:140}),b.expander.removeClass("expanded").addClass("collapsed"),a("html, body").animate({scrollTop:b.container.offset().top-20}),b.state=
"partial")})}var p=h.encodedReviews,m=parseInt(h.reviewsPerRow),t=0,v=0;h=a("#productDescription-multiColumn");var u={},n,q,r;0<h.length&&p&&0<p.length&&m&&(n=h.find(".reviewsExpander"),q=h.find(".seeMoreProductReviews"),d(),b())})});
/* ******** */
(function(l){var m=window.AmazonUIPageJS||window.P,n=m._namespace||m.attributeErrors,f=n?n("TwisterBooksDetailPageAsset",""):m;f.guardFatal?f.guardFatal(l)(f,window):f.execute(function(){l(f,window)})})(function(l,m,n){l.when("A","jQuery","atf").execute(function(f,a){f.on.ready(function(){function p(a,c){100>=c?g.count(a+"-count-0-100",c):1E3>=c?g.count(a+"-count-100-1000",c):1E3<c&&g.count(a+"-count-1000",c)}function n(b,c,d,f,e){a(b).slideToggle(300);a(c).slideToggle(300);a(d).toggleClass("tmmShowPrompt tmmHidePrompt");
a(f).toggleClass("tmmShowPrompt tmmHidePrompt");a(e).toggleClass("rotate")}function I(b){b.position();b.width();a(".swatchElement");b.find(".swatchElement").each(function(){a(this).attr("data-width",a(this).width());q+=a(this).width()});a("#formats").find(".a-row").removeClass("nonJSFormats")}function v(){var b=a("#formats.responsive");if(0!==b.length){var c=b.width()-40,d=0,f=0;b.find(".swatchElement").each(function(){a(this).is(":visible")?d+=a(this).width():f++});var e=a(b.find(".swatchElement").get().length),
t=b.find(".swatchElement .audibleTitle").length,h=0<e.length&&4<=e[0];(w||x)&&h&&t&&(h=J(d,c),d-=h,w?g.count("mediaMatrixUIOptimization",1):g.count("mediaMatrixUIOptimizationResizeAndSpillOver",1));d>c?a(b.find(".swatchElement:visible").get().reverse()).each(function(){var b=0,e=!1;a(this).find(".format").hasClass("a-button-selected")?(b=a(this).prev(".swatchElement").width(),e=a(this).prev(".swatchElement").is(":hidden"),a(this).prev(".swatchElement").hide()):(b=a(this).width(),e=a(this).is(":hidden"),
a(this).hide());f++;e||(d-=b);return d>c}):d<c&&b.find(".swatchElement").each(function(){if(a(this).is(":hidden")){var b=a(this).width();b<=c-d&&(a(this).show(),d+=b,f--)}});0==f&&K(d,c,e,q);(x||y)&&t&&(a("#tmmSwatches").css({display:"inline-block","white-space":"normal"}),y&&g.count("mediaMatrixtwisterSpillOver",1),a(b.find(".swatchElement").get().reverse()).each(function(){a(this).is(":hidden")&&a(this).show();a(this).addClass("marginTop")}));!z&&t&&(a.post("/hz/audible/wl",{audible_weblabs:"ADBL_TWISTER_RESIZE_116490"}),
z=1);A||(e=a("#audibleTwisterWeblabs"),null!=e&&e.length&&null!=e.data("weblabs")&&(e=e.data("weblabs"),b=b.find(".swatchElement:visible .audibleTitle").length,e.length&&b&&a.post("/hz/audible/wl",{audible_weblabs:e},function(a){A=!0})))}}function J(b,c){var d=a("#formats"),f=0;a(d.find(".swatchElement").get().reverse()).each(function(){var e=B(a(this)),d=a(this).width(),d=d>e?d-e:0;if(b>c&&0<d||a(this).is(":hidden"))C(a(this),e),f+=d,b-=d});return f}function K(b,c,d,f){var e=Math.round(0<d.length?
(c-b)/d[0]:0)-10,e=0<e?e:0;0<e&&a("#formats").find(".swatchElement").each(function(){var b=parseInt(a(this).attr("data-width")),d=B(a(this))+(0<e?e:0),b=f<c?b+1:Math.min(d,b);C(a(this),b)});return e}function B(a){var c=a.find("#kuBadge").length;a=a.find(".a-icon-kindle-unlimited").length;return 0<c||0<a?150:117}function C(a,c){a.addClass("resizedSwatchElement");a.css({width:c+"px"})}var D=0,E=0,A=!1,u,g=m.ue,q=0,z=0,w=a("#twisterResizeWeblab")?a("#twisterResizeWeblab").data("weblabs"):null,x=a("#twisterResizeAndSpillOver")?
a("#twisterResizeAndSpillOver").data("weblabs"):null,y=a("#twisterSpillOver")?a("#twisterSpillOver").data("weblabs"):null,F=function(a){"undefined"!=typeof a&&(u=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){F(m.DPClientLogger)}):l.when("DPClientLogger").execute(F);var h=f.state("mediamatrix-saf"),G=h&&h.hideEdition,r=h?h.editionCount:0;f.declarative("tmm-see-more-editions-click",["click"],function(b){var c=b.data,
d=c.metabindingUrl;if(b.$target.hasClass("a-link-expander")||b.$target.parent().hasClass("a-link-expander")){var c=c.metabindingPlaceHolder,g="#metabinding_row_top_"+c,e="#metabinding_row_bottom_"+c,h="#editionsSeePrompt_"+c,l="#editionsHidePrompt_"+c,p="#editionsIcon_"+c,r="isAjaxComplete_"+c,q="isAjaxInProgress_"+c;b="#tmmSpinnerDiv_"+c;var k=f.state("mediamatrix-state"),c=k["url_"+c].replace(/&amp;/g,"\x26");a("#formats .tmmErrorClass").hide();"1"===k[r]||"1"===k[q]?n(g,e,h,l,p):(f.ajax(c,{method:"get",
success:function(){k[r]="1";f.state("mediamatrix-state",k);n(g,e,h,l,p)},indicator:a(b),error:function(){a($tmmErrorDiv).show();k[q]="0";f.state("mediamatrix-state",k)}}),k[q]="1",f.state("mediamatrix-state",k))}else"#"!==d&&(m.location=d)});0<a("#formats \x3e .a-link-expander").length&&g&&g.count&&(G?(g.count("mediaMatrixExpanderPresent-saf",1),p("mediaMatrixExpanderPresent-saf",r)):(g.count("mediaMatrixExpanderPresent",1),p("mediaMatrixExpanderPresent",r)));a("#formats \x3e .a-link-expander").click(function(){n("#tmmSwatches",
"#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");E||(g&&g.count&&(G?(g.count("mediaMatrixExpanderClicked-saf",1),p("mediaMatrixExpanderClicked-saf",r)):(g.count("mediaMatrixExpanderClicked",1),p("mediaMatrixExpanderClicked",r))),E=1);u&&a("#twister").is(":visible")&&!D&&(u.logImpression("tmm-show-more-formats-viewed"),D=1)});a("#formats.responsive").each(function(){I(a(this))});var h=f.state("mediamatrixState"),H="false";"undefined"!==typeof h&&"undefined"!==typeof h.swatchWrap&&
(H=h.swatchWrap);"true"!=H&&(v(),f.on("resize",v));a("#formats .unselected .format").mouseenter(function(){a(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){a(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});a("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageBookProductDescriptionAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
