'use strict';mix_d("CerberusSharedCards__cerberus-shared:cerberus-shared__sN3ZheYJ","exports tslib @c/aui-truncate @c/logger @c/metrics @c/remote-operations @c/scoped-dom @c/aui-untrusted-ajax".split(" "),function(u,b,I,v,J,K,L,M){function m(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var N=m(I),h=m(J),O=m(K),p=m(L),P=m(M),Q=function(a,c,q){if(a){for(var k=[],b=0;b<a.length;b++){var e=a[b],f=c[b],g=q[b],d={};e.dataset.subasin&&(d.subsAsin=e.dataset.subasin);e.dataset.subasinprice&&
"true"!==f.dataset.isparent&&(d.subsPrice=parseFloat(e.dataset.subasinprice),d.subsIsParent=!1);e.dataset.subasincurrency&&(d.subsCurrency=e.dataset.subasincurrency);e.dataset.subasinrating&&(d.subsAvgRating=parseFloat(e.dataset.subasinrating));e.dataset.subasintotalreviews&&(d.subsTotalReviews=parseInt(e.dataset.subasintotalreviews.replace(/[.,\s]/g,""),10));e.dataset.subasinsourcesmap&&(d.subsSourcesMap=e.dataset.subasinsourcesmap);f.dataset&&f.dataset.lowestprice&&f.dataset.highestprice&&(d.subsPrice=
parseFloat(f.dataset.lowestprice),d.subsLowestPrice=parseFloat(f.dataset.lowestprice),d.subsHighestPrice=parseFloat(f.dataset.highestprice),d.subsIsParent=!0);d.subsPrimeEligible=g.dataset.isprime&&"true"===g.dataset.isprime?!0:!1;d.subsPosition=b;d.subsSource=null;d.subsSourceScore=null;k.push(d)}return k}},R=function(a){var c=a.asin,b=a.offerListingId,k=a.sessionId;a="/gp/add-to-cart/json/?ref_="+a.refmarker+"_"+c;return P["default"].post(a+("&verificationSessionID="+k+"&clientName=ReorderInnovations&ASIN="+
c+"&offerListingID="+b),{accepts:"application/json",contentType:"application/json"},{ASIN:c,clientName:"ReorderInnovations",offerListingID:b,verificationSessionID:k})},S=function(a,c,b){a&&c?a.$Nav&&"function"===typeof a.$Nav.when?a.$Nav.when("api.setCartCount").run(function(a){a(c)}):a.amazon&&a.amazon.mash&&a.amazon.mash.cart&&"function"===typeof a.amazon.mash.cart.didUpdate?a.amazon.mash.cart.didUpdate({newCartQuantity:c}):v.log("CerberusSharedCards.updateCartCount.deviceType."+b+".$Nav and mash missing",
"ERROR"):v.log("CerberusSharedCards.updateCartCount.deviceType."+b+".window."+a.toString()+".count."+c.toString()+".dependency missing","ERROR")},y=function(a,b,h,k){"undefined"===typeof k?(a.style.display="block",b.style.display="none",h.style.display="none"):k?(a.style.display="none",b.style.display="block",h.style.display="none"):(a.style.display="none",b.style.display="none",h.style.display="block")},T=function(a){a=a?a.dataset:{};return{deviceType:a.deviceType,seedAsin:a.landedAsin,subsReason:a.displayReason}};
u._operationNames=["addToCart","getCartCount"];u.card=function(){return b.__awaiter(void 0,void 0,void 0,function(){var a,c,q,k,m,e,f,g,d,z,w,C,l,u,A,B,D,n,E,r,F,x,G,H;return b.__generator(this,function(t){switch(t.label){case 0:a=O["default"].setup();c=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_style_landingPageData__26puO")[0];q=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_style_asinTitle__1nn_H");k=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_style_asinPriceRange__yoi8E");
m=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_style_primeBadge__2RNdQ");e=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_style_asinImage__3JG_P");f=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_actions_action__2rnkD");g=c.dataset.producerId;d=c.dataset.customerId||null;z=c.dataset.marketplaceId;w=c.dataset.sessionId;C=c.dataset.requestId;l=c.dataset.deviceType||"";u=c.dataset.reftag||"";A=T(c);B=Q(q,k,m);"prservices_dpx_percolate"===g?h["default"].count("prservices.ooswidget.shown."+
l,1):"prservices_fod_widget_feedback_loop"===g?h["default"].count("prservices.fodwidget.shown."+l,1):"prservices_cart_percolate"===g&&N["default"].refreshAutoTruncate();if(g){D=function(a){var c=q[a],e={subsAsin:(c?c.dataset:{}).subasin};a=b.__assign(b.__assign({customerId:d,obfuscatedMarketplaceId:z,sessionId:w},A),null===B||void 0===B?void 0:B[a]);h["default"].event(a,g,"prservices.SurfacedSubstituteEvent.6");var U=b.__assign(b.__assign({obfuscatedMarketplaceId:z,sessionId:w,surfacedAsinRequestId:C},
A),e);c.onclick=function(){return b.__awaiter(void 0,void 0,void 0,function(){return b.__generator(this,function(a){h["default"].event(U,g,"prservices.ClickedSubstituteEvent.3");return[2]})})}};for(n=0;n<q.length;n++)D(n);E=function(a){a=e[a];var c={subsAsin:(a?a.dataset:{}).subasin},d=b.__assign(b.__assign({obfuscatedMarketplaceId:z,sessionId:w,surfacedAsinRequestId:C},A),c);a.onclick=function(){return b.__awaiter(void 0,void 0,void 0,function(){return b.__generator(this,function(a){h["default"].event(d,
g,"prservices.ClickedSubstituteEvent.3");return[2]})})}};for(n=0;n<e.length;n++)E(n)}if(!(f&&0<f.length))return[3,5];r="prservices_cart_percolate"===g?"rsi.cart.":"rsi.oos.";h["default"].count(r+"atc.shown."+l,1);F="click";x=0;t.label=1;case 1:return t.trys.push([1,3,,4]),[4,a.getCartCount()];case 2:return G=t.sent(),x=G.items,[3,4];case 3:return H=t.sent(),v.log("CerberusSharedCards.getCartCount."+H.toString(),"ERROR"),[3,4];case 4:Array.prototype.forEach.call(f,function(a,b){var c=u+"_oos_atcajx_"+
l+"_"+b;b=a.querySelector("button");var d=a.querySelector("._cerberus-shared_actions_action-message-loading___LqSL"),e=a.querySelector("._cerberus-shared_actions_action-message-success__3NeI4"),f=a.querySelector("._cerberus-shared_actions_action-message-fail__1S0wg");a=b?b.dataset:{};var g=a.asin,k=a.offerlistingid;b.addEventListener(F,function(a){h["default"].count(r+"atc.click."+l,1);y(d,e,f,void 0);R({asin:g,offerListingId:k,refmarker:c,sessionId:w}).then(function(a){var b=a.responseBody;a=b.isOK;
b=b.cartQuantity;var c=parseInt(b,10);a&&x!==c?(x=c,h["default"].count(r+"atc.success."+l,1),S(window,parseInt(b,10),l),y(d,e,f,a),a=p["default"].cardRoot.getElementsByClassName("_cerberus-shared_style_addToCartClickedFlag__3rAXC"),0<a.length&&a[0].setAttribute("value","true")):(v.log("CerberusSharedCards.UATC.isOK."+a+".asin."+g+".cartCount."+x+".newCount."+c,a?"WARN":"ERROR"),y(d,e,f,!1),h["default"].count(r+"atc.fail."+l,1))}).catch(function(a){v.log("CerberusSharedCards.UATC."+a.toString(),"ERROR");
h["default"].count(r+"atc.fail."+l,1);y(d,e,f,!1)})})}),t.label=5;case 5:return[2]}})})}});
